.TH "BSL430_NET.FirmwareTools" 3 "Sat Jun 22 2019" "Version 1.2.1" "BSL430.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BSL430_NET.FirmwareTools
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFwExtensions\fP"
.br
.RI "Extensions class wrapping some extensions methods like CRC calc\&. "
.ti -1c
.RI "class \fBFwTools\fP"
.br
.RI "\fBUtility\fP class providing basic manipulation (Parse, Create, ConvertTo) with Intel-HEX, TI-TXT and ELF firmware formats\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BSL430\&.NET from the source code\&.
