.TH "BSL430_NET.Comm.Serial_Device" 3 "Sat Jun 22 2019" "Version 1.2.1" "BSL430.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BSL430_NET.Comm.Serial_Device \- Serial Device node extends generic \fBBsl430NetDevice\fP\&. Use requires library: SerialPortStream\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBBSL430_NET\&.Bsl430NetDevice\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSerial_Device\fP (string _port, string name, string desc, string fulldesc, \fBMode\fP mode)"
.br
.RI "\fBSerial_Device\fP constructor\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "readonly string \fBport\fP"
.br
.RI "Serial device port name\&. "
.in -1c
.SH "Detailed Description"
.PP 
Serial Device node extends generic \fBBsl430NetDevice\fP\&. Use requires library: SerialPortStream\&. 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "BSL430_NET\&.Comm\&.Serial_Device\&.Serial_Device (string _port, string name, string desc, string fulldesc, \fBMode\fP mode)"

.PP
\fBSerial_Device\fP constructor\&. 
.SH "Member Data Documentation"
.PP 
.SS "readonly string BSL430_NET\&.Comm\&.Serial_Device\&.port"

.PP
Serial device port name\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for BSL430\&.NET from the source code\&.
