.TH "BSL430_NET.Comm.USB_HID_Device" 3 "Sat Jun 22 2019" "Version 1.2.1" "BSL430.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BSL430_NET.Comm.USB_HID_Device \- USB HID Device node extends generic \fBBsl430NetDevice\fP\&. Use requires libraries: HidSharp, LibUsbDotNet\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBBSL430_NET\&.Bsl430NetDevice\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUSB_HID_Device\fP (int _vid, int _pid, string _serial, string _manufacturer, string _product_name, string name, string desc, string fulldesc, \fBMode\fP mode)"
.br
.RI "\fBUSB_HID_Device\fP constructor\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "readonly int \fBvid\fP"
.br
.RI "USB HID device VID\&. "
.ti -1c
.RI "readonly int \fBpid\fP"
.br
.RI "USB HID device PID\&. "
.ti -1c
.RI "readonly string \fBserial\fP"
.br
.RI "USB HID device serial number\&. "
.ti -1c
.RI "readonly string \fBmanufacturer\fP"
.br
.RI "USB HID device manufacturer\&. "
.ti -1c
.RI "readonly string \fBproduct_name\fP"
.br
.RI "USB HID device product name\&. "
.in -1c
.SH "Detailed Description"
.PP 
USB HID Device node extends generic \fBBsl430NetDevice\fP\&. Use requires libraries: HidSharp, LibUsbDotNet\&. 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "BSL430_NET\&.Comm\&.USB_HID_Device\&.USB_HID_Device (int _vid, int _pid, string _serial, string _manufacturer, string _product_name, string name, string desc, string fulldesc, \fBMode\fP mode)"

.PP
\fBUSB_HID_Device\fP constructor\&. 
.SH "Member Data Documentation"
.PP 
.SS "readonly string BSL430_NET\&.Comm\&.USB_HID_Device\&.manufacturer"

.PP
USB HID device manufacturer\&. 
.SS "readonly int BSL430_NET\&.Comm\&.USB_HID_Device\&.pid"

.PP
USB HID device PID\&. 
.SS "readonly string BSL430_NET\&.Comm\&.USB_HID_Device\&.product_name"

.PP
USB HID device product name\&. 
.SS "readonly string BSL430_NET\&.Comm\&.USB_HID_Device\&.serial"

.PP
USB HID device serial number\&. 
.SS "readonly int BSL430_NET\&.Comm\&.USB_HID_Device\&.vid"

.PP
USB HID device VID\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for BSL430\&.NET from the source code\&.
