.TH "BSL430_NET.Report" 3 "Sat Jun 22 2019" "Version 1.2.1" "BSL430.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BSL430_NET.Report \- \fBReport\fP is result of an action block with Name, Result and Timestamp\&.  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBName\fP = 'unknown report'\fC [get, set]\fP"
.br
.RI "\fBReport\fP Name is headline of action\&. "
.ti -1c
.RI "\fBReportResult\fP \fBResult\fP = \fBReportResult\&.FAILED\fP\fC [get, set]\fP"
.br
.RI "\fBReport\fP Result indicates the result of action\&. "
.ti -1c
.RI "DateTime \fBTimestamp\fP = DateTime\&.Now\fC [get, set]\fP"
.br
.RI "\fBReport\fP Timestamp is timestamp of \fBReport\fP creation\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBReport\fP is result of an action block with Name, Result and Timestamp\&. 


.SH "Property Documentation"
.PP 
.SS "string BSL430_NET\&.Report\&.Name = 'unknown report'\fC [get]\fP, \fC [set]\fP"

.PP
\fBReport\fP Name is headline of action\&. 
.SS "\fBReportResult\fP BSL430_NET\&.Report\&.Result = \fBReportResult\&.FAILED\fP\fC [get]\fP, \fC [set]\fP"

.PP
\fBReport\fP Result indicates the result of action\&. 
.SS "DateTime BSL430_NET\&.Report\&.Timestamp = DateTime\&.Now\fC [get]\fP, \fC [set]\fP"

.PP
\fBReport\fP Timestamp is timestamp of \fBReport\fP creation\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for BSL430\&.NET from the source code\&.
