.TH "BSL430_NET.Utility.Utils" 3 "Tue Sep 17 2019" "Version 1.3.4" "BSL430.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BSL430_NET.Utility.Utils
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBStatus\fP \fBStatusCreate\fP (int value)"
.br
.ti -1c
.RI "static \fBStatus\fP \fBStatusCreate\fP (int value, \fBStatus\fP stat)"
.br
.ti -1c
.RI "static \fBStatus\fP \fBStatusCreate\fP (int value, string extra)"
.br
.ti -1c
.RI "static \fBStatusEx\fP \fBStatusCreateEx\fP (int value)"
.br
.ti -1c
.RI "static \fBStatusEx\fP \fBStatusCreateEx\fP (int value, List< \fBReport\fP > reports, \fBReport\fP report, byte[] version, int bytes)"
.br
.ti -1c
.RI "static \fBStatusEx\fP \fBStatusCreateEx\fP (int value, \fBStatus\fP stat, List< \fBReport\fP > reports, \fBReport\fP report, byte[] version, int bytes)"
.br
.ti -1c
.RI "static \fBStatusEx\fP \fBStatusCreateEx\fP (int value, \fBStatus\fP stat, string extra, List< \fBReport\fP > reports, \fBReport\fP report, byte[] version, int bytes)"
.br
.ti -1c
.RI "static \fBStatusEx\fP \fBStatusCreateEx\fP (\fBStatus\fP status, List< \fBReport\fP > reports, \fBReport\fP report, byte[] version, int bytes)"
.br
.ti -1c
.RI "static \fBStatus\fP \fBStatusCreate\fP (int value, \fBStatus\fP stat=null, string extra='', byte[] data_tx=null, byte[] data_rx=null)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for BSL430\&.NET from the source code\&.
