.TH "BSL430_NET.FirmwareTools.FwTools.FwNode" 3 "Sat Jun 22 2019" "Version 1.2.1" "BSL430.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BSL430_NET.FirmwareTools.FwTools.FwNode \- Atomic unit which every firmware consits of representated by single byte with 16bit address\&.  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "byte \fBData\fP = 0xFF\fC [get, set]\fP"
.br
.RI "Data is single data byte with associated 16-bit address Addr\&. "
.ti -1c
.RI "int \fBAddr\fP = 0\fC [get, set]\fP"
.br
.RI "Addr is 16-bit address of Data byte\&. "
.in -1c
.SH "Detailed Description"
.PP 
Atomic unit which every firmware consits of representated by single byte with 16bit address\&. 


.SH "Property Documentation"
.PP 
.SS "int BSL430_NET\&.FirmwareTools\&.FwTools\&.FwNode\&.Addr = 0\fC [get]\fP, \fC [set]\fP"

.PP
Addr is 16-bit address of Data byte\&. 
.SS "byte BSL430_NET\&.FirmwareTools\&.FwTools\&.FwNode\&.Data = 0xFF\fC [get]\fP, \fC [set]\fP"

.PP
Data is single data byte with associated 16-bit address Addr\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for BSL430\&.NET from the source code\&.
