.TH "BSL430_NET.Comm.Serial_Device" 3 "Tue Sep 17 2019" "Version 1.3.4" "BSL430.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BSL430_NET.Comm.Serial_Device \- Serial Device node extends generic \fBBsl430NetDevice\fP\&. Use requires library: SerialPortStream\&. NOTE: If target app use \&.NET Framework 4\&.6\&.2 or lower, Nuget package: Microsoft\&.Win32\&.Registry is required!  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBBSL430_NET\&.Bsl430NetDevice\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSerial_Device\fP (string \fBPort\fP, string \fBName\fP, string Desc, string Fulldesc, \fBMode\fP \fBMode\fP)"
.br
.RI "\fBSerial_Device\fP constructor\&. "
.ti -1c
.RI "\fBSerial_Device\fP ()"
.br
.RI "\fBSerial_Device\fP parameterless constructor for serialization\&. "
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.RI "Short string general information about this device\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBPort\fP\fC [get, set]\fP"
.br
.RI "Serial device port name\&. "
.in -1c
.SH "Detailed Description"
.PP 
Serial Device node extends generic \fBBsl430NetDevice\fP\&. Use requires library: SerialPortStream\&. NOTE: If target app use \&.NET Framework 4\&.6\&.2 or lower, Nuget package: Microsoft\&.Win32\&.Registry is required! 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "BSL430_NET\&.Comm\&.Serial_Device\&.Serial_Device (string Port, string Name, string Desc, string Fulldesc, \fBMode\fP Mode)"

.PP
\fBSerial_Device\fP constructor\&. 
.SS "BSL430_NET\&.Comm\&.Serial_Device\&.Serial_Device ()"

.PP
\fBSerial_Device\fP parameterless constructor for serialization\&. 
.SH "Member Function Documentation"
.PP 
.SS "override string BSL430_NET\&.Comm\&.Serial_Device\&.ToString ()"

.PP
Short string general information about this device\&. 
.SH "Property Documentation"
.PP 
.SS "string BSL430_NET\&.Comm\&.Serial_Device\&.Port\fC [get]\fP, \fC [set]\fP"

.PP
Serial device port name\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for BSL430\&.NET from the source code\&.
