.TH "BSL430_NET.Utility" 3 "Sat Jun 22 2019" "Version 1.2.1" "BSL430.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BSL430_NET.Utility
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBExtensions\fP"
.br
.ti -1c
.RI "class \fBUtility\fP"
.br
.RI "\fBUtility\fP class providing some helpful methods\&. "
.ti -1c
.RI "class \fBUtils\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BSL430\&.NET from the source code\&.
