.TH "BSL430_NET.Comm.Libftdi_Device" 3 "Tue Sep 17 2019" "Version 1.3.4" "BSL430.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BSL430_NET.Comm.Libftdi_Device \- Libftdi Device node extends generic \fBBsl430NetDevice\fP\&. Use requires libraries: libftdi, libusb, LibUsbDotNet  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBBSL430_NET\&.Bsl430NetDevice\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLibftdi_Device\fP (int \fBVid\fP, int \fBPid\fP, string \fBName\fP, string Desc, string Fulldesc, \fBMode\fP \fBMode\fP)"
.br
.RI "\fBLibftdi_Device\fP constructor\&. "
.ti -1c
.RI "\fBLibftdi_Device\fP ()"
.br
.RI "\fBLibftdi_Device\fP parameterless constructor for serialization\&. "
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.RI "Short string general information about this device\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBVid\fP\fC [get, set]\fP"
.br
.RI "FTDI device VID eg\&. 0x0403\&. "
.ti -1c
.RI "int \fBPid\fP\fC [get, set]\fP"
.br
.RI "FTDI device PID eg\&. 0x6001\&. "
.in -1c
.SH "Detailed Description"
.PP 
Libftdi Device node extends generic \fBBsl430NetDevice\fP\&. Use requires libraries: libftdi, libusb, LibUsbDotNet 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "BSL430_NET\&.Comm\&.Libftdi_Device\&.Libftdi_Device (int Vid, int Pid, string Name, string Desc, string Fulldesc, \fBMode\fP Mode)"

.PP
\fBLibftdi_Device\fP constructor\&. 
.SS "BSL430_NET\&.Comm\&.Libftdi_Device\&.Libftdi_Device ()"

.PP
\fBLibftdi_Device\fP parameterless constructor for serialization\&. 
.SH "Member Function Documentation"
.PP 
.SS "override string BSL430_NET\&.Comm\&.Libftdi_Device\&.ToString ()"

.PP
Short string general information about this device\&. 
.SH "Property Documentation"
.PP 
.SS "int BSL430_NET\&.Comm\&.Libftdi_Device\&.Pid\fC [get]\fP, \fC [set]\fP"

.PP
FTDI device PID eg\&. 0x6001\&. 
.SS "int BSL430_NET\&.Comm\&.Libftdi_Device\&.Vid\fC [get]\fP, \fC [set]\fP"

.PP
FTDI device VID eg\&. 0x0403\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for BSL430\&.NET from the source code\&.
