.TH "BSL430_NET.Bsl430NetEventArgs" 3 "Sat Jun 22 2019" "Version 1.2.1" "BSL430.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BSL430_NET.Bsl430NetEventArgs \- BSL430\&.NET Event Args\&. Progress is double percentage and \fBReport\fP is current action\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits EventArgs\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "double \fBProgress\fP\fC [get, set]\fP"
.br
.RI "0-100% value indicating current progress of main action (Upload, Download, Erase) "
.ti -1c
.RI "\fBReport\fP \fBReport\fP\fC [get, set]\fP"
.br
.RI "Current report which is in progress at the moment\&. "
.in -1c
.SH "Detailed Description"
.PP 
BSL430\&.NET Event Args\&. Progress is double percentage and \fBReport\fP is current action\&. 


.SH "Property Documentation"
.PP 
.SS "double BSL430_NET\&.Bsl430NetEventArgs\&.Progress\fC [get]\fP, \fC [set]\fP"

.PP
0-100% value indicating current progress of main action (Upload, Download, Erase) 
.SS "\fBReport\fP BSL430_NET\&.Bsl430NetEventArgs\&.Report\fC [get]\fP, \fC [set]\fP"

.PP
Current report which is in progress at the moment\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for BSL430\&.NET from the source code\&.
