.TH "BSL430_NET.Extensions" 3 "Tue Sep 17 2019" "Version 1.3.4" "BSL430.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BSL430_NET.Extensions \- Extension class with some helpful methods\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static string \fBToHexString\fP (this byte[] ba)"
.br
.RI "Converts byte array to hex string\&. "
.ti -1c
.RI "static IEnumerable< Enum > \fBGetFlags\fP (this Enum input)"
.br
.RI "Gets all enum flags\&. "
.ti -1c
.RI "static string \fBGetEnumDescription\fP (this Enum value)"
.br
.RI "Gets enum string description\&. "
.ti -1c
.RI "static string \fBTruncate\fP (this string value, int maxChars, string postfix='\&.\&.\&.')"
.br
.RI "Truncate string with a postfix or three dots by default\&. "
.in -1c
.SH "Detailed Description"
.PP 
Extension class with some helpful methods\&. 


.SH "Member Function Documentation"
.PP 
.SS "static string BSL430_NET\&.Extensions\&.GetEnumDescription (this Enum value)\fC [static]\fP"

.PP
Gets enum string description\&. 
.SS "static IEnumerable<Enum> BSL430_NET\&.Extensions\&.GetFlags (this Enum input)\fC [static]\fP"

.PP
Gets all enum flags\&. 
.SS "static string BSL430_NET\&.Extensions\&.ToHexString (this byte[] ba)\fC [static]\fP"

.PP
Converts byte array to hex string\&. 
.SS "static string BSL430_NET\&.Extensions\&.Truncate (this string value, int maxChars, string postfix = \fC'\&.\&.\&.'\fP)\fC [static]\fP"

.PP
Truncate string with a postfix or three dots by default\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for BSL430\&.NET from the source code\&.
