.TH "FTD2XX_NET.FTDI.FT_DATA_BITS" 3 "Sat Jun 22 2019" "Version 1.2.1" "BSL430.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FTD2XX_NET.FTDI.FT_DATA_BITS \- Permitted data bits for \fBFTDI\fP devices  

.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const byte \fBFT_BITS_8\fP = 0x08"
.br
.RI "8 data bits "
.ti -1c
.RI "const byte \fBFT_BITS_7\fP = 0x07"
.br
.RI "7 data bits "
.in -1c
.SH "Detailed Description"
.PP 
Permitted data bits for \fBFTDI\fP devices 


.SH "Member Data Documentation"
.PP 
.SS "const byte FTD2XX_NET\&.FTDI\&.FT_DATA_BITS\&.FT_BITS_7 = 0x07"

.PP
7 data bits 
.SS "const byte FTD2XX_NET\&.FTDI\&.FT_DATA_BITS\&.FT_BITS_8 = 0x08"

.PP
8 data bits 

.SH "Author"
.PP 
Generated automatically by Doxygen for BSL430\&.NET from the source code\&.
