.TH "FTD2XX_NET.FTDI.FT_LINE_STATUS" 3 "Sat Jun 22 2019" "Version 1.2.1" "BSL430.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FTD2XX_NET.FTDI.FT_LINE_STATUS \- Line status bit definitions  

.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const byte \fBFT_OE\fP = 0x02"
.br
.RI "Overrun Error (OE) line status "
.ti -1c
.RI "const byte \fBFT_PE\fP = 0x04"
.br
.RI "Parity Error (PE) line status "
.ti -1c
.RI "const byte \fBFT_FE\fP = 0x08"
.br
.RI "Framing Error (FE) line status "
.ti -1c
.RI "const byte \fBFT_BI\fP = 0x10"
.br
.RI "Break Interrupt (BI) line status "
.in -1c
.SH "Detailed Description"
.PP 
Line status bit definitions 


.SH "Member Data Documentation"
.PP 
.SS "const byte FTD2XX_NET\&.FTDI\&.FT_LINE_STATUS\&.FT_BI = 0x10"

.PP
Break Interrupt (BI) line status 
.SS "const byte FTD2XX_NET\&.FTDI\&.FT_LINE_STATUS\&.FT_FE = 0x08"

.PP
Framing Error (FE) line status 
.SS "const byte FTD2XX_NET\&.FTDI\&.FT_LINE_STATUS\&.FT_OE = 0x02"

.PP
Overrun Error (OE) line status 
.SS "const byte FTD2XX_NET\&.FTDI\&.FT_LINE_STATUS\&.FT_PE = 0x04"

.PP
Parity Error (PE) line status 

.SH "Author"
.PP 
Generated automatically by Doxygen for BSL430\&.NET from the source code\&.
