.TH "FTD2XX_NET.FTDI.FT_STOP_BITS" 3 "Sat Jun 22 2019" "Version 1.2.1" "BSL430.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FTD2XX_NET.FTDI.FT_STOP_BITS \- Permitted stop bits for \fBFTDI\fP devices  

.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const byte \fBFT_STOP_BITS_1\fP = 0x00"
.br
.RI "1 stop bit "
.ti -1c
.RI "const byte \fBFT_STOP_BITS_2\fP = 0x02"
.br
.RI "2 stop bits "
.in -1c
.SH "Detailed Description"
.PP 
Permitted stop bits for \fBFTDI\fP devices 


.SH "Member Data Documentation"
.PP 
.SS "const byte FTD2XX_NET\&.FTDI\&.FT_STOP_BITS\&.FT_STOP_BITS_1 = 0x00"

.PP
1 stop bit 
.SS "const byte FTD2XX_NET\&.FTDI\&.FT_STOP_BITS\&.FT_STOP_BITS_2 = 0x02"

.PP
2 stop bits 

.SH "Author"
.PP 
Generated automatically by Doxygen for BSL430\&.NET from the source code\&.
