.TH "FTD2XX_NET.FTDI.FT_DRIVE_CURRENT" 3 "Sat Jun 22 2019" "Version 1.2.1" "BSL430.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FTD2XX_NET.FTDI.FT_DRIVE_CURRENT \- Valid values for drive current options on FT2232H, FT4232H and FT232H devices\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const byte \fBFT_DRIVE_CURRENT_4MA\fP = 4"
.br
.RI "4mA drive current "
.ti -1c
.RI "const byte \fBFT_DRIVE_CURRENT_8MA\fP = 8"
.br
.RI "8mA drive current "
.ti -1c
.RI "const byte \fBFT_DRIVE_CURRENT_12MA\fP = 12"
.br
.RI "12mA drive current "
.ti -1c
.RI "const byte \fBFT_DRIVE_CURRENT_16MA\fP = 16"
.br
.RI "16mA drive current "
.in -1c
.SH "Detailed Description"
.PP 
Valid values for drive current options on FT2232H, FT4232H and FT232H devices\&. 


.SH "Member Data Documentation"
.PP 
.SS "const byte FTD2XX_NET\&.FTDI\&.FT_DRIVE_CURRENT\&.FT_DRIVE_CURRENT_12MA = 12"

.PP
12mA drive current 
.SS "const byte FTD2XX_NET\&.FTDI\&.FT_DRIVE_CURRENT\&.FT_DRIVE_CURRENT_16MA = 16"

.PP
16mA drive current 
.SS "const byte FTD2XX_NET\&.FTDI\&.FT_DRIVE_CURRENT\&.FT_DRIVE_CURRENT_4MA = 4"

.PP
4mA drive current 
.SS "const byte FTD2XX_NET\&.FTDI\&.FT_DRIVE_CURRENT\&.FT_DRIVE_CURRENT_8MA = 8"

.PP
8mA drive current 

.SH "Author"
.PP 
Generated automatically by Doxygen for BSL430\&.NET from the source code\&.
