.TH "FTD2XX_NET.FTDI.FT232R_EEPROM_STRUCTURE" 3 "Sat Jun 22 2019" "Version 1.2.1" "BSL430.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FTD2XX_NET.FTDI.FT232R_EEPROM_STRUCTURE \- EEPROM structure specific to FT232R and FT245R devices\&. Inherits from \fBFT_EEPROM_DATA\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFTD2XX_NET\&.FTDI\&.FT_EEPROM_DATA\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBUseExtOsc\fP = false"
.br
.RI "Disables the FT232R internal clock source\&. "
.ti -1c
.RI "bool \fBHighDriveIOs\fP = false"
.br
.RI "Enables high current IOs "
.ti -1c
.RI "byte \fBEndpointSize\fP = 64"
.br
.RI "Sets the endpoint size\&. This should always be set to 64 "
.ti -1c
.RI "bool \fBPullDownEnable\fP = false"
.br
.RI "Determines if IOs are pulled down when the device is in suspend "
.ti -1c
.RI "bool \fBSerNumEnable\fP = true"
.br
.RI "Determines if the serial number is enabled "
.ti -1c
.RI "bool \fBInvertTXD\fP = false"
.br
.RI "Inverts the sense of the TXD line "
.ti -1c
.RI "bool \fBInvertRXD\fP = false"
.br
.RI "Inverts the sense of the RXD line "
.ti -1c
.RI "bool \fBInvertRTS\fP = false"
.br
.RI "Inverts the sense of the RTS line "
.ti -1c
.RI "bool \fBInvertCTS\fP = false"
.br
.RI "Inverts the sense of the CTS line "
.ti -1c
.RI "bool \fBInvertDTR\fP = false"
.br
.RI "Inverts the sense of the DTR line "
.ti -1c
.RI "bool \fBInvertDSR\fP = false"
.br
.RI "Inverts the sense of the DSR line "
.ti -1c
.RI "bool \fBInvertDCD\fP = false"
.br
.RI "Inverts the sense of the DCD line "
.ti -1c
.RI "bool \fBInvertRI\fP = false"
.br
.RI "Inverts the sense of the RI line "
.ti -1c
.RI "byte \fBCbus0\fP = \fBFT_CBUS_OPTIONS\&.FT_CBUS_SLEEP\fP"
.br
.RI "Sets the function of the CBUS0 pin for FT232R devices\&. Valid values are FT_CBUS_TXDEN, FT_CBUS_PWRON , FT_CBUS_RXLED, FT_CBUS_TXLED, FT_CBUS_TXRXLED, FT_CBUS_SLEEP, FT_CBUS_CLK48, FT_CBUS_CLK24, FT_CBUS_CLK12, FT_CBUS_CLK6, FT_CBUS_IOMODE, FT_CBUS_BITBANG_WR, FT_CBUS_BITBANG_RD "
.ti -1c
.RI "byte \fBCbus1\fP = \fBFT_CBUS_OPTIONS\&.FT_CBUS_SLEEP\fP"
.br
.RI "Sets the function of the CBUS1 pin for FT232R devices\&. Valid values are FT_CBUS_TXDEN, FT_CBUS_PWRON , FT_CBUS_RXLED, FT_CBUS_TXLED, FT_CBUS_TXRXLED, FT_CBUS_SLEEP, FT_CBUS_CLK48, FT_CBUS_CLK24, FT_CBUS_CLK12, FT_CBUS_CLK6, FT_CBUS_IOMODE, FT_CBUS_BITBANG_WR, FT_CBUS_BITBANG_RD "
.ti -1c
.RI "byte \fBCbus2\fP = \fBFT_CBUS_OPTIONS\&.FT_CBUS_SLEEP\fP"
.br
.RI "Sets the function of the CBUS2 pin for FT232R devices\&. Valid values are FT_CBUS_TXDEN, FT_CBUS_PWRON , FT_CBUS_RXLED, FT_CBUS_TXLED, FT_CBUS_TXRXLED, FT_CBUS_SLEEP, FT_CBUS_CLK48, FT_CBUS_CLK24, FT_CBUS_CLK12, FT_CBUS_CLK6, FT_CBUS_IOMODE, FT_CBUS_BITBANG_WR, FT_CBUS_BITBANG_RD "
.ti -1c
.RI "byte \fBCbus3\fP = \fBFT_CBUS_OPTIONS\&.FT_CBUS_SLEEP\fP"
.br
.RI "Sets the function of the CBUS3 pin for FT232R devices\&. Valid values are FT_CBUS_TXDEN, FT_CBUS_PWRON , FT_CBUS_RXLED, FT_CBUS_TXLED, FT_CBUS_TXRXLED, FT_CBUS_SLEEP, FT_CBUS_CLK48, FT_CBUS_CLK24, FT_CBUS_CLK12, FT_CBUS_CLK6, FT_CBUS_IOMODE, FT_CBUS_BITBANG_WR, FT_CBUS_BITBANG_RD "
.ti -1c
.RI "byte \fBCbus4\fP = \fBFT_CBUS_OPTIONS\&.FT_CBUS_SLEEP\fP"
.br
.RI "Sets the function of the CBUS4 pin for FT232R devices\&. Valid values are FT_CBUS_TXDEN, FT_CBUS_PWRON , FT_CBUS_RXLED, FT_CBUS_TXLED, FT_CBUS_TXRXLED, FT_CBUS_SLEEP, FT_CBUS_CLK48, FT_CBUS_CLK24, FT_CBUS_CLK12, FT_CBUS_CLK6 "
.ti -1c
.RI "bool \fBRIsD2XX\fP = false"
.br
.RI "Determines if the VCP driver is loaded "
.in -1c
.SH "Detailed Description"
.PP 
EEPROM structure specific to FT232R and FT245R devices\&. Inherits from \fBFT_EEPROM_DATA\fP\&. 


.SH "Member Data Documentation"
.PP 
.SS "byte FTD2XX_NET\&.FTDI\&.FT232R_EEPROM_STRUCTURE\&.Cbus0 = \fBFT_CBUS_OPTIONS\&.FT_CBUS_SLEEP\fP"

.PP
Sets the function of the CBUS0 pin for FT232R devices\&. Valid values are FT_CBUS_TXDEN, FT_CBUS_PWRON , FT_CBUS_RXLED, FT_CBUS_TXLED, FT_CBUS_TXRXLED, FT_CBUS_SLEEP, FT_CBUS_CLK48, FT_CBUS_CLK24, FT_CBUS_CLK12, FT_CBUS_CLK6, FT_CBUS_IOMODE, FT_CBUS_BITBANG_WR, FT_CBUS_BITBANG_RD 
.SS "byte FTD2XX_NET\&.FTDI\&.FT232R_EEPROM_STRUCTURE\&.Cbus1 = \fBFT_CBUS_OPTIONS\&.FT_CBUS_SLEEP\fP"

.PP
Sets the function of the CBUS1 pin for FT232R devices\&. Valid values are FT_CBUS_TXDEN, FT_CBUS_PWRON , FT_CBUS_RXLED, FT_CBUS_TXLED, FT_CBUS_TXRXLED, FT_CBUS_SLEEP, FT_CBUS_CLK48, FT_CBUS_CLK24, FT_CBUS_CLK12, FT_CBUS_CLK6, FT_CBUS_IOMODE, FT_CBUS_BITBANG_WR, FT_CBUS_BITBANG_RD 
.SS "byte FTD2XX_NET\&.FTDI\&.FT232R_EEPROM_STRUCTURE\&.Cbus2 = \fBFT_CBUS_OPTIONS\&.FT_CBUS_SLEEP\fP"

.PP
Sets the function of the CBUS2 pin for FT232R devices\&. Valid values are FT_CBUS_TXDEN, FT_CBUS_PWRON , FT_CBUS_RXLED, FT_CBUS_TXLED, FT_CBUS_TXRXLED, FT_CBUS_SLEEP, FT_CBUS_CLK48, FT_CBUS_CLK24, FT_CBUS_CLK12, FT_CBUS_CLK6, FT_CBUS_IOMODE, FT_CBUS_BITBANG_WR, FT_CBUS_BITBANG_RD 
.SS "byte FTD2XX_NET\&.FTDI\&.FT232R_EEPROM_STRUCTURE\&.Cbus3 = \fBFT_CBUS_OPTIONS\&.FT_CBUS_SLEEP\fP"

.PP
Sets the function of the CBUS3 pin for FT232R devices\&. Valid values are FT_CBUS_TXDEN, FT_CBUS_PWRON , FT_CBUS_RXLED, FT_CBUS_TXLED, FT_CBUS_TXRXLED, FT_CBUS_SLEEP, FT_CBUS_CLK48, FT_CBUS_CLK24, FT_CBUS_CLK12, FT_CBUS_CLK6, FT_CBUS_IOMODE, FT_CBUS_BITBANG_WR, FT_CBUS_BITBANG_RD 
.SS "byte FTD2XX_NET\&.FTDI\&.FT232R_EEPROM_STRUCTURE\&.Cbus4 = \fBFT_CBUS_OPTIONS\&.FT_CBUS_SLEEP\fP"

.PP
Sets the function of the CBUS4 pin for FT232R devices\&. Valid values are FT_CBUS_TXDEN, FT_CBUS_PWRON , FT_CBUS_RXLED, FT_CBUS_TXLED, FT_CBUS_TXRXLED, FT_CBUS_SLEEP, FT_CBUS_CLK48, FT_CBUS_CLK24, FT_CBUS_CLK12, FT_CBUS_CLK6 
.SS "byte FTD2XX_NET\&.FTDI\&.FT232R_EEPROM_STRUCTURE\&.EndpointSize = 64"

.PP
Sets the endpoint size\&. This should always be set to 64 
.SS "bool FTD2XX_NET\&.FTDI\&.FT232R_EEPROM_STRUCTURE\&.HighDriveIOs = false"

.PP
Enables high current IOs 
.SS "bool FTD2XX_NET\&.FTDI\&.FT232R_EEPROM_STRUCTURE\&.InvertCTS = false"

.PP
Inverts the sense of the CTS line 
.SS "bool FTD2XX_NET\&.FTDI\&.FT232R_EEPROM_STRUCTURE\&.InvertDCD = false"

.PP
Inverts the sense of the DCD line 
.SS "bool FTD2XX_NET\&.FTDI\&.FT232R_EEPROM_STRUCTURE\&.InvertDSR = false"

.PP
Inverts the sense of the DSR line 
.SS "bool FTD2XX_NET\&.FTDI\&.FT232R_EEPROM_STRUCTURE\&.InvertDTR = false"

.PP
Inverts the sense of the DTR line 
.SS "bool FTD2XX_NET\&.FTDI\&.FT232R_EEPROM_STRUCTURE\&.InvertRI = false"

.PP
Inverts the sense of the RI line 
.SS "bool FTD2XX_NET\&.FTDI\&.FT232R_EEPROM_STRUCTURE\&.InvertRTS = false"

.PP
Inverts the sense of the RTS line 
.SS "bool FTD2XX_NET\&.FTDI\&.FT232R_EEPROM_STRUCTURE\&.InvertRXD = false"

.PP
Inverts the sense of the RXD line 
.SS "bool FTD2XX_NET\&.FTDI\&.FT232R_EEPROM_STRUCTURE\&.InvertTXD = false"

.PP
Inverts the sense of the TXD line 
.SS "bool FTD2XX_NET\&.FTDI\&.FT232R_EEPROM_STRUCTURE\&.PullDownEnable = false"

.PP
Determines if IOs are pulled down when the device is in suspend 
.SS "bool FTD2XX_NET\&.FTDI\&.FT232R_EEPROM_STRUCTURE\&.RIsD2XX = false"

.PP
Determines if the VCP driver is loaded 
.SS "bool FTD2XX_NET\&.FTDI\&.FT232R_EEPROM_STRUCTURE\&.SerNumEnable = true"

.PP
Determines if the serial number is enabled 
.SS "bool FTD2XX_NET\&.FTDI\&.FT232R_EEPROM_STRUCTURE\&.UseExtOsc = false"

.PP
Disables the FT232R internal clock source\&. If the device has external oscillator enabled it must have an external oscillator fitted to function 

.SH "Author"
.PP 
Generated automatically by Doxygen for BSL430\&.NET from the source code\&.
