.TH "FTD2XX_NET.FTDI.FT_XSERIES_CBUS_OPTIONS" 3 "Sat Jun 22 2019" "Version 1.2.1" "BSL430.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FTD2XX_NET.FTDI.FT_XSERIES_CBUS_OPTIONS \- Available functions for the X-Series CBUS pins\&. Controlled by X-Series EEPROM settings  

.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const byte \fBFT_CBUS_TRISTATE\fP = 0x00"
.br
.RI "FT X-Series CBUS EEPROM options - Tristate "
.ti -1c
.RI "const byte \fBFT_CBUS_RXLED\fP = 0x01"
.br
.RI "FT X-Series CBUS EEPROM options - RxLED# "
.ti -1c
.RI "const byte \fBFT_CBUS_TXLED\fP = 0x02"
.br
.RI "FT X-Series CBUS EEPROM options - TxLED# "
.ti -1c
.RI "const byte \fBFT_CBUS_TXRXLED\fP = 0x03"
.br
.RI "FT X-Series CBUS EEPROM options - TxRxLED# "
.ti -1c
.RI "const byte \fBFT_CBUS_PWREN\fP = 0x04"
.br
.RI "FT X-Series CBUS EEPROM options - PwrEn# "
.ti -1c
.RI "const byte \fBFT_CBUS_SLEEP\fP = 0x05"
.br
.RI "FT X-Series CBUS EEPROM options - Sleep# "
.ti -1c
.RI "const byte \fBFT_CBUS_Drive_0\fP = 0x06"
.br
.RI "FT X-Series CBUS EEPROM options - Drive_0 "
.ti -1c
.RI "const byte \fBFT_CBUS_Drive_1\fP = 0x07"
.br
.RI "FT X-Series CBUS EEPROM options - Drive_1 "
.ti -1c
.RI "const byte \fBFT_CBUS_GPIO\fP = 0x08"
.br
.RI "FT X-Series CBUS EEPROM options - GPIO "
.ti -1c
.RI "const byte \fBFT_CBUS_TXDEN\fP = 0x09"
.br
.RI "FT X-Series CBUS EEPROM options - TxdEn "
.ti -1c
.RI "const byte \fBFT_CBUS_CLK24MHz\fP = 0x0A"
.br
.RI "FT X-Series CBUS EEPROM options - Clk24MHz "
.ti -1c
.RI "const byte \fBFT_CBUS_CLK12MHz\fP = 0x0B"
.br
.RI "FT X-Series CBUS EEPROM options - Clk12MHz "
.ti -1c
.RI "const byte \fBFT_CBUS_CLK6MHz\fP = 0x0C"
.br
.RI "FT X-Series CBUS EEPROM options - Clk6MHz "
.ti -1c
.RI "const byte \fBFT_CBUS_BCD_Charger\fP = 0x0D"
.br
.RI "FT X-Series CBUS EEPROM options - BCD_Charger "
.ti -1c
.RI "const byte \fBFT_CBUS_BCD_Charger_N\fP = 0x0E"
.br
.RI "FT X-Series CBUS EEPROM options - BCD_Charger# "
.ti -1c
.RI "const byte \fBFT_CBUS_I2C_TXE\fP = 0x0F"
.br
.RI "FT X-Series CBUS EEPROM options - I2C_TXE# "
.ti -1c
.RI "const byte \fBFT_CBUS_I2C_RXF\fP = 0x10"
.br
.RI "FT X-Series CBUS EEPROM options - I2C_RXF# "
.ti -1c
.RI "const byte \fBFT_CBUS_VBUS_Sense\fP = 0x11"
.br
.RI "FT X-Series CBUS EEPROM options - VBUS_Sense "
.ti -1c
.RI "const byte \fBFT_CBUS_BitBang_WR\fP = 0x12"
.br
.RI "FT X-Series CBUS EEPROM options - BitBang_WR# "
.ti -1c
.RI "const byte \fBFT_CBUS_BitBang_RD\fP = 0x13"
.br
.RI "FT X-Series CBUS EEPROM options - BitBang_RD# "
.ti -1c
.RI "const byte \fBFT_CBUS_Time_Stamp\fP = 0x14"
.br
.RI "FT X-Series CBUS EEPROM options - Time_Stampe "
.ti -1c
.RI "const byte \fBFT_CBUS_Keep_Awake\fP = 0x15"
.br
.RI "FT X-Series CBUS EEPROM options - Keep_Awake# "
.in -1c
.SH "Detailed Description"
.PP 
Available functions for the X-Series CBUS pins\&. Controlled by X-Series EEPROM settings 


.SH "Member Data Documentation"
.PP 
.SS "const byte FTD2XX_NET\&.FTDI\&.FT_XSERIES_CBUS_OPTIONS\&.FT_CBUS_BCD_Charger = 0x0D"

.PP
FT X-Series CBUS EEPROM options - BCD_Charger 
.SS "const byte FTD2XX_NET\&.FTDI\&.FT_XSERIES_CBUS_OPTIONS\&.FT_CBUS_BCD_Charger_N = 0x0E"

.PP
FT X-Series CBUS EEPROM options - BCD_Charger# 
.SS "const byte FTD2XX_NET\&.FTDI\&.FT_XSERIES_CBUS_OPTIONS\&.FT_CBUS_BitBang_RD = 0x13"

.PP
FT X-Series CBUS EEPROM options - BitBang_RD# 
.SS "const byte FTD2XX_NET\&.FTDI\&.FT_XSERIES_CBUS_OPTIONS\&.FT_CBUS_BitBang_WR = 0x12"

.PP
FT X-Series CBUS EEPROM options - BitBang_WR# 
.SS "const byte FTD2XX_NET\&.FTDI\&.FT_XSERIES_CBUS_OPTIONS\&.FT_CBUS_CLK12MHz = 0x0B"

.PP
FT X-Series CBUS EEPROM options - Clk12MHz 
.SS "const byte FTD2XX_NET\&.FTDI\&.FT_XSERIES_CBUS_OPTIONS\&.FT_CBUS_CLK24MHz = 0x0A"

.PP
FT X-Series CBUS EEPROM options - Clk24MHz 
.SS "const byte FTD2XX_NET\&.FTDI\&.FT_XSERIES_CBUS_OPTIONS\&.FT_CBUS_CLK6MHz = 0x0C"

.PP
FT X-Series CBUS EEPROM options - Clk6MHz 
.SS "const byte FTD2XX_NET\&.FTDI\&.FT_XSERIES_CBUS_OPTIONS\&.FT_CBUS_Drive_0 = 0x06"

.PP
FT X-Series CBUS EEPROM options - Drive_0 
.SS "const byte FTD2XX_NET\&.FTDI\&.FT_XSERIES_CBUS_OPTIONS\&.FT_CBUS_Drive_1 = 0x07"

.PP
FT X-Series CBUS EEPROM options - Drive_1 
.SS "const byte FTD2XX_NET\&.FTDI\&.FT_XSERIES_CBUS_OPTIONS\&.FT_CBUS_GPIO = 0x08"

.PP
FT X-Series CBUS EEPROM options - GPIO 
.SS "const byte FTD2XX_NET\&.FTDI\&.FT_XSERIES_CBUS_OPTIONS\&.FT_CBUS_I2C_RXF = 0x10"

.PP
FT X-Series CBUS EEPROM options - I2C_RXF# 
.SS "const byte FTD2XX_NET\&.FTDI\&.FT_XSERIES_CBUS_OPTIONS\&.FT_CBUS_I2C_TXE = 0x0F"

.PP
FT X-Series CBUS EEPROM options - I2C_TXE# 
.SS "const byte FTD2XX_NET\&.FTDI\&.FT_XSERIES_CBUS_OPTIONS\&.FT_CBUS_Keep_Awake = 0x15"

.PP
FT X-Series CBUS EEPROM options - Keep_Awake# 
.SS "const byte FTD2XX_NET\&.FTDI\&.FT_XSERIES_CBUS_OPTIONS\&.FT_CBUS_PWREN = 0x04"

.PP
FT X-Series CBUS EEPROM options - PwrEn# 
.SS "const byte FTD2XX_NET\&.FTDI\&.FT_XSERIES_CBUS_OPTIONS\&.FT_CBUS_RXLED = 0x01"

.PP
FT X-Series CBUS EEPROM options - RxLED# 
.SS "const byte FTD2XX_NET\&.FTDI\&.FT_XSERIES_CBUS_OPTIONS\&.FT_CBUS_SLEEP = 0x05"

.PP
FT X-Series CBUS EEPROM options - Sleep# 
.SS "const byte FTD2XX_NET\&.FTDI\&.FT_XSERIES_CBUS_OPTIONS\&.FT_CBUS_Time_Stamp = 0x14"

.PP
FT X-Series CBUS EEPROM options - Time_Stampe 
.SS "const byte FTD2XX_NET\&.FTDI\&.FT_XSERIES_CBUS_OPTIONS\&.FT_CBUS_TRISTATE = 0x00"

.PP
FT X-Series CBUS EEPROM options - Tristate 
.SS "const byte FTD2XX_NET\&.FTDI\&.FT_XSERIES_CBUS_OPTIONS\&.FT_CBUS_TXDEN = 0x09"

.PP
FT X-Series CBUS EEPROM options - TxdEn 
.SS "const byte FTD2XX_NET\&.FTDI\&.FT_XSERIES_CBUS_OPTIONS\&.FT_CBUS_TXLED = 0x02"

.PP
FT X-Series CBUS EEPROM options - TxLED# 
.SS "const byte FTD2XX_NET\&.FTDI\&.FT_XSERIES_CBUS_OPTIONS\&.FT_CBUS_TXRXLED = 0x03"

.PP
FT X-Series CBUS EEPROM options - TxRxLED# 
.SS "const byte FTD2XX_NET\&.FTDI\&.FT_XSERIES_CBUS_OPTIONS\&.FT_CBUS_VBUS_Sense = 0x11"

.PP
FT X-Series CBUS EEPROM options - VBUS_Sense 

.SH "Author"
.PP 
Generated automatically by Doxygen for BSL430\&.NET from the source code\&.
