.TH "FTD2XX_NET.FTDI.FT232H_EEPROM_STRUCTURE" 3 "Sat Jun 22 2019" "Version 1.2.1" "BSL430.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FTD2XX_NET.FTDI.FT232H_EEPROM_STRUCTURE \- EEPROM structure specific to FT232H devices\&. Inherits from \fBFT_EEPROM_DATA\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFTD2XX_NET\&.FTDI\&.FT_EEPROM_DATA\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBPullDownEnable\fP = false"
.br
.RI "Determines if IOs are pulled down when the device is in suspend "
.ti -1c
.RI "bool \fBSerNumEnable\fP = true"
.br
.RI "Determines if the serial number is enabled "
.ti -1c
.RI "bool \fBACSlowSlew\fP = false"
.br
.RI "Determines if AC pins have a slow slew rate "
.ti -1c
.RI "bool \fBACSchmittInput\fP = false"
.br
.RI "Determines if the AC pins have a Schmitt input "
.ti -1c
.RI "byte \fBACDriveCurrent\fP = \fBFT_DRIVE_CURRENT\&.FT_DRIVE_CURRENT_4MA\fP"
.br
.RI "Determines the AC pins drive current in mA\&. Valid values are FT_DRIVE_CURRENT_4MA, FT_DRIVE_CURRENT_8MA, FT_DRIVE_CURRENT_12MA or FT_DRIVE_CURRENT_16MA "
.ti -1c
.RI "bool \fBADSlowSlew\fP = false"
.br
.RI "Determines if AD pins have a slow slew rate "
.ti -1c
.RI "bool \fBADSchmittInput\fP = false"
.br
.RI "Determines if the AD pins have a Schmitt input "
.ti -1c
.RI "byte \fBADDriveCurrent\fP = \fBFT_DRIVE_CURRENT\&.FT_DRIVE_CURRENT_4MA\fP"
.br
.RI "Determines the AD pins drive current in mA\&. Valid values are FT_DRIVE_CURRENT_4MA, FT_DRIVE_CURRENT_8MA, FT_DRIVE_CURRENT_12MA or FT_DRIVE_CURRENT_16MA "
.ti -1c
.RI "byte \fBCbus0\fP = \fBFT_232H_CBUS_OPTIONS\&.FT_CBUS_TRISTATE\fP"
.br
.RI "Sets the function of the CBUS0 pin for FT232H devices\&. Valid values are FT_CBUS_TRISTATE, FT_CBUS_RXLED, FT_CBUS_TXLED, FT_CBUS_TXRXLED, FT_CBUS_PWREN, FT_CBUS_SLEEP, FT_CBUS_DRIVE_0, FT_CBUS_DRIVE_1, FT_CBUS_TXDEN, FT_CBUS_CLK30, FT_CBUS_CLK15, FT_CBUS_CLK7_5 "
.ti -1c
.RI "byte \fBCbus1\fP = \fBFT_232H_CBUS_OPTIONS\&.FT_CBUS_TRISTATE\fP"
.br
.RI "Sets the function of the CBUS1 pin for FT232H devices\&. Valid values are FT_CBUS_TRISTATE, FT_CBUS_RXLED, FT_CBUS_TXLED, FT_CBUS_TXRXLED, FT_CBUS_PWREN, FT_CBUS_SLEEP, FT_CBUS_DRIVE_0, FT_CBUS_DRIVE_1, FT_CBUS_TXDEN, FT_CBUS_CLK30, FT_CBUS_CLK15, FT_CBUS_CLK7_5 "
.ti -1c
.RI "byte \fBCbus2\fP = \fBFT_232H_CBUS_OPTIONS\&.FT_CBUS_TRISTATE\fP"
.br
.RI "Sets the function of the CBUS2 pin for FT232H devices\&. Valid values are FT_CBUS_TRISTATE, FT_CBUS_RXLED, FT_CBUS_TXLED, FT_CBUS_TXRXLED, FT_CBUS_PWREN, FT_CBUS_SLEEP, FT_CBUS_DRIVE_0, FT_CBUS_DRIVE_1, FT_CBUS_TXDEN "
.ti -1c
.RI "byte \fBCbus3\fP = \fBFT_232H_CBUS_OPTIONS\&.FT_CBUS_TRISTATE\fP"
.br
.RI "Sets the function of the CBUS3 pin for FT232H devices\&. Valid values are FT_CBUS_TRISTATE, FT_CBUS_RXLED, FT_CBUS_TXLED, FT_CBUS_TXRXLED, FT_CBUS_PWREN, FT_CBUS_SLEEP, FT_CBUS_DRIVE_0, FT_CBUS_DRIVE_1, FT_CBUS_TXDEN "
.ti -1c
.RI "byte \fBCbus4\fP = \fBFT_232H_CBUS_OPTIONS\&.FT_CBUS_TRISTATE\fP"
.br
.RI "Sets the function of the CBUS4 pin for FT232H devices\&. Valid values are FT_CBUS_TRISTATE, FT_CBUS_RXLED, FT_CBUS_TXLED, FT_CBUS_TXRXLED, FT_CBUS_PWREN, FT_CBUS_SLEEP, FT_CBUS_DRIVE_0, FT_CBUS_DRIVE_1, FT_CBUS_TXDEN "
.ti -1c
.RI "byte \fBCbus5\fP = \fBFT_232H_CBUS_OPTIONS\&.FT_CBUS_TRISTATE\fP"
.br
.RI "Sets the function of the CBUS5 pin for FT232H devices\&. Valid values are FT_CBUS_TRISTATE, FT_CBUS_RXLED, FT_CBUS_TXLED, FT_CBUS_TXRXLED, FT_CBUS_PWREN, FT_CBUS_SLEEP, FT_CBUS_DRIVE_0, FT_CBUS_DRIVE_1, FT_CBUS_IOMODE, FT_CBUS_TXDEN, FT_CBUS_CLK30, FT_CBUS_CLK15, FT_CBUS_CLK7_5 "
.ti -1c
.RI "byte \fBCbus6\fP = \fBFT_232H_CBUS_OPTIONS\&.FT_CBUS_TRISTATE\fP"
.br
.RI "Sets the function of the CBUS6 pin for FT232H devices\&. Valid values are FT_CBUS_TRISTATE, FT_CBUS_RXLED, FT_CBUS_TXLED, FT_CBUS_TXRXLED, FT_CBUS_PWREN, FT_CBUS_SLEEP, FT_CBUS_DRIVE_0, FT_CBUS_DRIVE_1, FT_CBUS_IOMODE, FT_CBUS_TXDEN, FT_CBUS_CLK30, FT_CBUS_CLK15, FT_CBUS_CLK7_5 "
.ti -1c
.RI "byte \fBCbus7\fP = \fBFT_232H_CBUS_OPTIONS\&.FT_CBUS_TRISTATE\fP"
.br
.RI "Sets the function of the CBUS7 pin for FT232H devices\&. Valid values are FT_CBUS_TRISTATE "
.ti -1c
.RI "byte \fBCbus8\fP = \fBFT_232H_CBUS_OPTIONS\&.FT_CBUS_TRISTATE\fP"
.br
.RI "Sets the function of the CBUS8 pin for FT232H devices\&. Valid values are FT_CBUS_TRISTATE, FT_CBUS_RXLED, FT_CBUS_TXLED, FT_CBUS_TXRXLED, FT_CBUS_PWREN, FT_CBUS_SLEEP, FT_CBUS_DRIVE_0, FT_CBUS_DRIVE_1, FT_CBUS_IOMODE, FT_CBUS_TXDEN, FT_CBUS_CLK30, FT_CBUS_CLK15, FT_CBUS_CLK7_5 "
.ti -1c
.RI "byte \fBCbus9\fP = \fBFT_232H_CBUS_OPTIONS\&.FT_CBUS_TRISTATE\fP"
.br
.RI "Sets the function of the CBUS9 pin for FT232H devices\&. Valid values are FT_CBUS_TRISTATE, FT_CBUS_RXLED, FT_CBUS_TXLED, FT_CBUS_TXRXLED, FT_CBUS_PWREN, FT_CBUS_SLEEP, FT_CBUS_DRIVE_0, FT_CBUS_DRIVE_1, FT_CBUS_IOMODE, FT_CBUS_TXDEN, FT_CBUS_CLK30, FT_CBUS_CLK15, FT_CBUS_CLK7_5 "
.ti -1c
.RI "bool \fBIsFifo\fP = false"
.br
.RI "Determines if the device is in FIFO mode "
.ti -1c
.RI "bool \fBIsFifoTar\fP = false"
.br
.RI "Determines if the device is in FIFO target mode "
.ti -1c
.RI "bool \fBIsFastSer\fP = false"
.br
.RI "Determines if the device is in fast serial mode "
.ti -1c
.RI "bool \fBIsFT1248\fP = false"
.br
.RI "Determines if the device is in FT1248 mode "
.ti -1c
.RI "bool \fBFT1248Cpol\fP = false"
.br
.RI "Determines FT1248 mode clock polarity "
.ti -1c
.RI "bool \fBFT1248Lsb\fP = false"
.br
.RI "Determines if data is ent MSB (0) or LSB (1) in FT1248 mode "
.ti -1c
.RI "bool \fBFT1248FlowControl\fP = false"
.br
.RI "Determines if FT1248 mode uses flow control "
.ti -1c
.RI "bool \fBIsVCP\fP = true"
.br
.RI "Determines if the VCP driver is loaded "
.ti -1c
.RI "bool \fBPowerSaveEnable\fP = false"
.br
.RI "For self-powered designs, keeps the FT232H in low power state until ACBUS7 is high "
.in -1c
.SH "Detailed Description"
.PP 
EEPROM structure specific to FT232H devices\&. Inherits from \fBFT_EEPROM_DATA\fP\&. 


.SH "Member Data Documentation"
.PP 
.SS "byte FTD2XX_NET\&.FTDI\&.FT232H_EEPROM_STRUCTURE\&.ACDriveCurrent = \fBFT_DRIVE_CURRENT\&.FT_DRIVE_CURRENT_4MA\fP"

.PP
Determines the AC pins drive current in mA\&. Valid values are FT_DRIVE_CURRENT_4MA, FT_DRIVE_CURRENT_8MA, FT_DRIVE_CURRENT_12MA or FT_DRIVE_CURRENT_16MA 
.SS "bool FTD2XX_NET\&.FTDI\&.FT232H_EEPROM_STRUCTURE\&.ACSchmittInput = false"

.PP
Determines if the AC pins have a Schmitt input 
.SS "bool FTD2XX_NET\&.FTDI\&.FT232H_EEPROM_STRUCTURE\&.ACSlowSlew = false"

.PP
Determines if AC pins have a slow slew rate 
.SS "byte FTD2XX_NET\&.FTDI\&.FT232H_EEPROM_STRUCTURE\&.ADDriveCurrent = \fBFT_DRIVE_CURRENT\&.FT_DRIVE_CURRENT_4MA\fP"

.PP
Determines the AD pins drive current in mA\&. Valid values are FT_DRIVE_CURRENT_4MA, FT_DRIVE_CURRENT_8MA, FT_DRIVE_CURRENT_12MA or FT_DRIVE_CURRENT_16MA 
.SS "bool FTD2XX_NET\&.FTDI\&.FT232H_EEPROM_STRUCTURE\&.ADSchmittInput = false"

.PP
Determines if the AD pins have a Schmitt input 
.SS "bool FTD2XX_NET\&.FTDI\&.FT232H_EEPROM_STRUCTURE\&.ADSlowSlew = false"

.PP
Determines if AD pins have a slow slew rate 
.SS "byte FTD2XX_NET\&.FTDI\&.FT232H_EEPROM_STRUCTURE\&.Cbus0 = \fBFT_232H_CBUS_OPTIONS\&.FT_CBUS_TRISTATE\fP"

.PP
Sets the function of the CBUS0 pin for FT232H devices\&. Valid values are FT_CBUS_TRISTATE, FT_CBUS_RXLED, FT_CBUS_TXLED, FT_CBUS_TXRXLED, FT_CBUS_PWREN, FT_CBUS_SLEEP, FT_CBUS_DRIVE_0, FT_CBUS_DRIVE_1, FT_CBUS_TXDEN, FT_CBUS_CLK30, FT_CBUS_CLK15, FT_CBUS_CLK7_5 
.SS "byte FTD2XX_NET\&.FTDI\&.FT232H_EEPROM_STRUCTURE\&.Cbus1 = \fBFT_232H_CBUS_OPTIONS\&.FT_CBUS_TRISTATE\fP"

.PP
Sets the function of the CBUS1 pin for FT232H devices\&. Valid values are FT_CBUS_TRISTATE, FT_CBUS_RXLED, FT_CBUS_TXLED, FT_CBUS_TXRXLED, FT_CBUS_PWREN, FT_CBUS_SLEEP, FT_CBUS_DRIVE_0, FT_CBUS_DRIVE_1, FT_CBUS_TXDEN, FT_CBUS_CLK30, FT_CBUS_CLK15, FT_CBUS_CLK7_5 
.SS "byte FTD2XX_NET\&.FTDI\&.FT232H_EEPROM_STRUCTURE\&.Cbus2 = \fBFT_232H_CBUS_OPTIONS\&.FT_CBUS_TRISTATE\fP"

.PP
Sets the function of the CBUS2 pin for FT232H devices\&. Valid values are FT_CBUS_TRISTATE, FT_CBUS_RXLED, FT_CBUS_TXLED, FT_CBUS_TXRXLED, FT_CBUS_PWREN, FT_CBUS_SLEEP, FT_CBUS_DRIVE_0, FT_CBUS_DRIVE_1, FT_CBUS_TXDEN 
.SS "byte FTD2XX_NET\&.FTDI\&.FT232H_EEPROM_STRUCTURE\&.Cbus3 = \fBFT_232H_CBUS_OPTIONS\&.FT_CBUS_TRISTATE\fP"

.PP
Sets the function of the CBUS3 pin for FT232H devices\&. Valid values are FT_CBUS_TRISTATE, FT_CBUS_RXLED, FT_CBUS_TXLED, FT_CBUS_TXRXLED, FT_CBUS_PWREN, FT_CBUS_SLEEP, FT_CBUS_DRIVE_0, FT_CBUS_DRIVE_1, FT_CBUS_TXDEN 
.SS "byte FTD2XX_NET\&.FTDI\&.FT232H_EEPROM_STRUCTURE\&.Cbus4 = \fBFT_232H_CBUS_OPTIONS\&.FT_CBUS_TRISTATE\fP"

.PP
Sets the function of the CBUS4 pin for FT232H devices\&. Valid values are FT_CBUS_TRISTATE, FT_CBUS_RXLED, FT_CBUS_TXLED, FT_CBUS_TXRXLED, FT_CBUS_PWREN, FT_CBUS_SLEEP, FT_CBUS_DRIVE_0, FT_CBUS_DRIVE_1, FT_CBUS_TXDEN 
.SS "byte FTD2XX_NET\&.FTDI\&.FT232H_EEPROM_STRUCTURE\&.Cbus5 = \fBFT_232H_CBUS_OPTIONS\&.FT_CBUS_TRISTATE\fP"

.PP
Sets the function of the CBUS5 pin for FT232H devices\&. Valid values are FT_CBUS_TRISTATE, FT_CBUS_RXLED, FT_CBUS_TXLED, FT_CBUS_TXRXLED, FT_CBUS_PWREN, FT_CBUS_SLEEP, FT_CBUS_DRIVE_0, FT_CBUS_DRIVE_1, FT_CBUS_IOMODE, FT_CBUS_TXDEN, FT_CBUS_CLK30, FT_CBUS_CLK15, FT_CBUS_CLK7_5 
.SS "byte FTD2XX_NET\&.FTDI\&.FT232H_EEPROM_STRUCTURE\&.Cbus6 = \fBFT_232H_CBUS_OPTIONS\&.FT_CBUS_TRISTATE\fP"

.PP
Sets the function of the CBUS6 pin for FT232H devices\&. Valid values are FT_CBUS_TRISTATE, FT_CBUS_RXLED, FT_CBUS_TXLED, FT_CBUS_TXRXLED, FT_CBUS_PWREN, FT_CBUS_SLEEP, FT_CBUS_DRIVE_0, FT_CBUS_DRIVE_1, FT_CBUS_IOMODE, FT_CBUS_TXDEN, FT_CBUS_CLK30, FT_CBUS_CLK15, FT_CBUS_CLK7_5 
.SS "byte FTD2XX_NET\&.FTDI\&.FT232H_EEPROM_STRUCTURE\&.Cbus7 = \fBFT_232H_CBUS_OPTIONS\&.FT_CBUS_TRISTATE\fP"

.PP
Sets the function of the CBUS7 pin for FT232H devices\&. Valid values are FT_CBUS_TRISTATE 
.SS "byte FTD2XX_NET\&.FTDI\&.FT232H_EEPROM_STRUCTURE\&.Cbus8 = \fBFT_232H_CBUS_OPTIONS\&.FT_CBUS_TRISTATE\fP"

.PP
Sets the function of the CBUS8 pin for FT232H devices\&. Valid values are FT_CBUS_TRISTATE, FT_CBUS_RXLED, FT_CBUS_TXLED, FT_CBUS_TXRXLED, FT_CBUS_PWREN, FT_CBUS_SLEEP, FT_CBUS_DRIVE_0, FT_CBUS_DRIVE_1, FT_CBUS_IOMODE, FT_CBUS_TXDEN, FT_CBUS_CLK30, FT_CBUS_CLK15, FT_CBUS_CLK7_5 
.SS "byte FTD2XX_NET\&.FTDI\&.FT232H_EEPROM_STRUCTURE\&.Cbus9 = \fBFT_232H_CBUS_OPTIONS\&.FT_CBUS_TRISTATE\fP"

.PP
Sets the function of the CBUS9 pin for FT232H devices\&. Valid values are FT_CBUS_TRISTATE, FT_CBUS_RXLED, FT_CBUS_TXLED, FT_CBUS_TXRXLED, FT_CBUS_PWREN, FT_CBUS_SLEEP, FT_CBUS_DRIVE_0, FT_CBUS_DRIVE_1, FT_CBUS_IOMODE, FT_CBUS_TXDEN, FT_CBUS_CLK30, FT_CBUS_CLK15, FT_CBUS_CLK7_5 
.SS "bool FTD2XX_NET\&.FTDI\&.FT232H_EEPROM_STRUCTURE\&.FT1248Cpol = false"

.PP
Determines FT1248 mode clock polarity 
.SS "bool FTD2XX_NET\&.FTDI\&.FT232H_EEPROM_STRUCTURE\&.FT1248FlowControl = false"

.PP
Determines if FT1248 mode uses flow control 
.SS "bool FTD2XX_NET\&.FTDI\&.FT232H_EEPROM_STRUCTURE\&.FT1248Lsb = false"

.PP
Determines if data is ent MSB (0) or LSB (1) in FT1248 mode 
.SS "bool FTD2XX_NET\&.FTDI\&.FT232H_EEPROM_STRUCTURE\&.IsFastSer = false"

.PP
Determines if the device is in fast serial mode 
.SS "bool FTD2XX_NET\&.FTDI\&.FT232H_EEPROM_STRUCTURE\&.IsFifo = false"

.PP
Determines if the device is in FIFO mode 
.SS "bool FTD2XX_NET\&.FTDI\&.FT232H_EEPROM_STRUCTURE\&.IsFifoTar = false"

.PP
Determines if the device is in FIFO target mode 
.SS "bool FTD2XX_NET\&.FTDI\&.FT232H_EEPROM_STRUCTURE\&.IsFT1248 = false"

.PP
Determines if the device is in FT1248 mode 
.SS "bool FTD2XX_NET\&.FTDI\&.FT232H_EEPROM_STRUCTURE\&.IsVCP = true"

.PP
Determines if the VCP driver is loaded 
.SS "bool FTD2XX_NET\&.FTDI\&.FT232H_EEPROM_STRUCTURE\&.PowerSaveEnable = false"

.PP
For self-powered designs, keeps the FT232H in low power state until ACBUS7 is high 
.SS "bool FTD2XX_NET\&.FTDI\&.FT232H_EEPROM_STRUCTURE\&.PullDownEnable = false"

.PP
Determines if IOs are pulled down when the device is in suspend 
.SS "bool FTD2XX_NET\&.FTDI\&.FT232H_EEPROM_STRUCTURE\&.SerNumEnable = true"

.PP
Determines if the serial number is enabled 

.SH "Author"
.PP 
Generated automatically by Doxygen for BSL430\&.NET from the source code\&.
