.TH "libftdinet.FTDIContext" 3 "Sat Jun 22 2019" "Version 1.2.1" "BSL430.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libftdinet.FTDIContext
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFTDIContext\fP (Object obj)"
.br
.ti -1c
.RI "\fBFTDIContext\fP (int vendor, int product)"
.br
.ti -1c
.RI "\fBFTDIContext\fP (int vendor, int product, string description, string serial)"
.br
.ti -1c
.RI "\fBFTDIContext\fP (IntPtr dev)"
.br
.ti -1c
.RI "void \fBReset\fP ()"
.br
.ti -1c
.RI "void \fBClose\fP ()"
.br
.ti -1c
.RI "void \fBPurgeBuffers\fP ()"
.br
.ti -1c
.RI "void \fBWriteEEPROM\fP (\fBftdi_eeprom\fP eeprom)"
.br
.ti -1c
.RI "void \fBEraseEEPROM\fP ()"
.br
.ti -1c
.RI "byte [] \fBReadEEPROM\fP ()"
.br
.ti -1c
.RI "int \fBReadData\fP (byte[] buf, int size)"
.br
.ti -1c
.RI "int \fBWriteData\fP (byte[] buf, int size)"
.br
.ti -1c
.RI "byte \fBGetPins\fP ()"
.br
.ti -1c
.RI "void \fBEnableBitBang\fP (byte bitmask)"
.br
.ti -1c
.RI "void \fBDisableBitBang\fP ()"
.br
.ti -1c
.RI "void \fBSetBitMode\fP (byte bitmask, byte mode)"
.br
.ti -1c
.RI "void \fBSetLineProperty\fP (BitsType bits, StopBitsType sbit, ParityType parity)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBBaudrate\fP\fC [set]\fP"
.br
.ti -1c
.RI "int \fBFlowControl\fP\fC [set]\fP"
.br
.ti -1c
.RI "int \fBSetRTS\fP\fC [set]\fP"
.br
.ti -1c
.RI "int \fBSetDTR\fP\fC [set]\fP"
.br
.ti -1c
.RI "uint \fBReadChunkSize\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "uint \fBWriteChunkSize\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "byte \fBLatencyTimer\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "Interface \fBInterface\fP\fC [set]\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for BSL430\&.NET from the source code\&.
