.TH "RJCP.IO.Ports.Native.Windows.NativeMethods.COMMTIMEOUTS" 3 "Sat Jun 22 2019" "Version 1.2.1" "BSL430.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RJCP.IO.Ports.Native.Windows.NativeMethods.COMMTIMEOUTS
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBReadIntervalTimeout\fP"
.br
.ti -1c
.RI "int \fBReadTotalTimeoutMultiplier\fP"
.br
.ti -1c
.RI "int \fBReadTotalTimeoutConstant\fP"
.br
.ti -1c
.RI "int \fBWriteTotalTimeoutMultiplier\fP"
.br
.ti -1c
.RI "int \fBWriteTotalTimeoutConstant\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for BSL430\&.NET from the source code\&.
