.TH "RJCP.IO.Ports.Native.ReadToCache" 3 "Sat Jun 22 2019" "Version 1.2.1" "BSL430.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RJCP.IO.Ports.Native.ReadToCache
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBRead\fP (\fBSerialBuffer\fP sbuffer, char[] cbuffer, int offset, int count)"
.br
.RI "Reads characters from the byte buffer into the character buffer, consuming data from the byte buffer\&. "
.ti -1c
.RI "int \fBReadChar\fP (\fBSerialBuffer\fP sbuffer)"
.br
.RI "Synchronously reads one character from the \fBSerialPortStream\fP input buffer\&. "
.ti -1c
.RI "bool \fBReadTo\fP (\fBSerialBuffer\fP sbuffer, string text, out string line)"
.br
.RI "Reads from the cached and byte stream looking for the text specified\&. "
.ti -1c
.RI "bool \fBReadToWaitForNewData\fP (\fBSerialBuffer\fP sbuffer, int timeout)"
.br
.RI "Waits for new data to arrive that can be used to recheck for new data\&. "
.ti -1c
.RI "string \fBReadExisting\fP (\fBSerialBuffer\fP sbuffer)"
.br
.RI "Reads all immediately available bytes\&. "
.ti -1c
.RI "void \fBReset\fP (bool withOverflow)"
.br
.RI "Resets the cache, taking optionally into account a previous overflow\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "Encoding \fBEncoding\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the byte encoding for pre- and post-transmission conversion of text\&. "
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "int RJCP\&.IO\&.Ports\&.Native\&.ReadToCache\&.Read (\fBSerialBuffer\fP sbuffer, char [] cbuffer, int offset, int count)"

.PP
Reads characters from the byte buffer into the character buffer, consuming data from the byte buffer\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsbuffer\fP The byte buffer to read from\&.
.br
\fIcbuffer\fP The character buffer to write to\&.
.br
\fIoffset\fP The offset to write to in \fIcbuffer\fP \&.
.br
\fIcount\fP The number of characters to read into \fIcbuffer\fP \&.
.RE
.PP
\fBReturns:\fP
.RS 4
The number of bytes read into \fIcbuffer\fP \&.
.RE
.PP
.PP
Data is read from the read byte buffer kept in \fIsbuffer\fP , converted using the decoder into \fIcbuffer\fP \&. As data is read from sbuffer, it is consumed\&. 
.SS "int RJCP\&.IO\&.Ports\&.Native\&.ReadToCache\&.ReadChar (\fBSerialBuffer\fP sbuffer)"

.PP
Synchronously reads one character from the \fBSerialPortStream\fP input buffer\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsbuffer\fP The byte buffer to read from\&.
.RE
.PP
\fBReturns:\fP
.RS 4
The character that was read\&. -1 indicates no data was available within the time out\&.
.RE
.PP

.SS "string RJCP\&.IO\&.Ports\&.Native\&.ReadToCache\&.ReadExisting (\fBSerialBuffer\fP sbuffer)"

.PP
Reads all immediately available bytes\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsbuffer\fP The byte buffer to read from\&.
.RE
.PP
\fBReturns:\fP
.RS 4
The contents of the stream and the input buffer of the \fBSerialPortStream\fP\&.
.RE
.PP

.SS "bool RJCP\&.IO\&.Ports\&.Native\&.ReadToCache\&.ReadTo (\fBSerialBuffer\fP sbuffer, string text, out string line)"

.PP
Reads from the cached and byte stream looking for the text specified\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsbuffer\fP The byte buffer to read from\&.
.br
\fItext\fP The text to indicate where the read operation stops\&.
.br
\fIline\fP On success, contains the line up to the text string requested\&.
.RE
.PP
\fBReturns:\fP
.RS 4
\fCtrue\fP if a line was found; \fCfalse\fP otherwise\&.
.RE
.PP

.SS "bool RJCP\&.IO\&.Ports\&.Native\&.ReadToCache\&.ReadToWaitForNewData (\fBSerialBuffer\fP sbuffer, int timeout)"

.PP
Waits for new data to arrive that can be used to recheck for new data\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsbuffer\fP The byte buffer to read from\&.
.br
\fItimeout\fP The time out in milliseconds\&.
.RE
.PP
\fBReturns:\fP
.RS 4
\fCtrue\fP if one more byte is available since the last \fBReadTo\fP call; \fCfalse\fP otherwise
.RE
.PP

.SS "void RJCP\&.IO\&.Ports\&.Native\&.ReadToCache\&.Reset (bool withOverflow)"

.PP
Resets the cache, taking optionally into account a previous overflow\&. 
.PP
\fBParameters:\fP
.RS 4
\fIwithOverflow\fP if set to \fCtrue\fP a previous overflow is taken into account and reinserted into the buffer, as if the first character had already been read\&.
.RE
.PP

.SH "Property Documentation"
.PP 
.SS "Encoding RJCP\&.IO\&.Ports\&.Native\&.ReadToCache\&.Encoding\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the byte encoding for pre- and post-transmission conversion of text\&. The encoding is used for encoding string information to byte format when sending over the serial port, or receiving data via the serial port\&. It is only used with the read/write functions that accept strings (and not used for byte based reading and writing)\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for BSL430\&.NET from the source code\&.
