.TH "RJCP.IO.Ports.Native.Unix.SafeSerialHandle" 3 "Sat Jun 22 2019" "Version 1.2.1" "BSL430.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RJCP.IO.Ports.Native.Unix.SafeSerialHandle
.SH SYNOPSIS
.br
.PP
.PP
Inherits SafeHandle\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override bool \fBReleaseHandle\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override bool \fBIsInvalid\fP\fC [get]\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for BSL430\&.NET from the source code\&.
