.TH "RJCP.IO.Ports.Native" 3 "Sat Jun 22 2019" "Version 1.2.1" "BSL430.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RJCP.IO.Ports.Native
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "interface \fBINativeSerial\fP"
.br
.RI "Interface for accessing serial based streams\&. "
.ti -1c
.RI "interface \fBISerialBufferSerialData\fP"
.br
.RI "Container structure for properties and methods related to the \fBNative\fP Serial object\&. "
.ti -1c
.RI "interface \fBISerialBufferStreamData\fP"
.br
.RI "Container structure for properties and methods related to the Stream object\&. "
.ti -1c
.RI "class \fBPlatform\fP"
.br
.ti -1c
.RI "class \fBReadToCache\fP"
.br
.ti -1c
.RI "class \fBSerialBuffer\fP"
.br
.RI "Manages two buffers, for reading and writing, between a Stream and a \fBNative\fP Serial object\&. "
.ti -1c
.RI "class \fBUnixNativeSerial\fP"
.br
.RI "\fBWindows\fP implementation for a \fBNative\fP Serial connection\&. "
.ti -1c
.RI "class \fBWinNativeSerial\fP"
.br
.RI "\fBWindows\fP implementation for a \fBNative\fP Serial connection\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BSL430\&.NET from the source code\&.
