.TH "RJCP.IO.Ports.SerialDataReceivedEventArgs" 3 "Sat Jun 22 2019" "Version 1.2.1" "BSL430.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RJCP.IO.Ports.SerialDataReceivedEventArgs \- EventArgs for DataReceived\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits EventArgs\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSerialDataReceivedEventArgs\fP (\fBSerialData\fP eventType)"
.br
.RI "Constructor\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBSerialData\fP \fBEventType\fP\fC [get]\fP"
.br
.RI "The event type for DataReceived\&. "
.in -1c
.SH "Detailed Description"
.PP 
EventArgs for DataReceived\&. 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "RJCP\&.IO\&.Ports\&.SerialDataReceivedEventArgs\&.SerialDataReceivedEventArgs (\fBSerialData\fP eventType)"

.PP
Constructor\&. 
.PP
\fBParameters:\fP
.RS 4
\fIeventType\fP Event that occurred\&.
.RE
.PP

.SH "Property Documentation"
.PP 
.SS "\fBSerialData\fP RJCP\&.IO\&.Ports\&.SerialDataReceivedEventArgs\&.EventType\fC [get]\fP"

.PP
The event type for DataReceived\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for BSL430\&.NET from the source code\&.
