.TH "RJCP.Datastructures" 3 "Sat Jun 22 2019" "Version 1.2.1" "BSL430.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RJCP.Datastructures
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCircularBuffer\fP"
.br
.RI "A simple datastructure to manage an array as a circular buffer\&. "
.ti -1c
.RI "class \fBCircularBufferExtensions\fP"
.br
.RI "A set of useful extensions to the \fBCircularBuffer\fP for specific data types\&. "
.ti -1c
.RI "class \fBReusableList\fP"
.br
.RI "Array of elements which can be reused\&. "
.ti -1c
.RI "class \fBTimerExpiry\fP"
.br
.RI "A class to maintain how much time is remaining since the last reset, until expiry\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BSL430\&.NET from the source code\&.
