.TH "RJCP.IO.Ports.Native.Windows.CommOverlappedIo" 3 "Sat Jun 22 2019" "Version 1.2.1" "BSL430.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RJCP.IO.Ports.Native.Windows.CommOverlappedIo
.SH SYNOPSIS
.br
.PP
.PP
Inherits IDisposable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCommOverlappedIo\fP (SafeFileHandle handle)"
.br
.RI "Initializes a new instance of the \fBCommOverlappedIo\fP class\&. "
.ti -1c
.RI "void \fBDiscardOutBuffer\fP ()"
.br
.RI "Discards data from the serial driver's transmit buffer\&. "
.ti -1c
.RI "void \fBStart\fP (\fBSerialBuffer\fP buffer, string name)"
.br
.RI "Start the I/O thread\&. "
.ti -1c
.RI "void \fBDispose\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBOnCommEvent\fP (\fBCommEventArgs\fP args)"
.br
.ti -1c
.RI "virtual void \fBOnCommErrorEvent\fP (\fBCommErrorEventArgs\fP args)"
.br
.ti -1c
.RI "virtual void \fBDispose\fP (bool disposing)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBBytesToRead\fP\fC [get]\fP"
.br
.RI "Gets the number of bytes in the driver queue still to be read\&. "
.ti -1c
.RI "int \fBBytesToWrite\fP\fC [get]\fP"
.br
.RI "Gets the number bytes to of data in the transmit buffer\&. "
.ti -1c
.RI "bool \fBIsRunning\fP\fC [get]\fP"
.br
.RI "Test if the I/O thread is running\&. "
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "EventHandler< \fBCommEventArgs\fP > \fBCommEvent\fP"
.br
.ti -1c
.RI "EventHandler< \fBCommErrorEventArgs\fP > \fBCommErrorEvent\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RJCP\&.IO\&.Ports\&.Native\&.Windows\&.CommOverlappedIo\&.CommOverlappedIo (SafeFileHandle handle)"

.PP
Initializes a new instance of the \fBCommOverlappedIo\fP class\&. 
.PP
\fBParameters:\fP
.RS 4
\fIhandle\fP The serial port handle\&.
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void RJCP\&.IO\&.Ports\&.Native\&.Windows\&.CommOverlappedIo\&.DiscardOutBuffer ()"

.PP
Discards data from the serial driver's transmit buffer\&. This function will discard the receive buffer of the \fBSerialPortStream\fP\&. 
.SS "void RJCP\&.IO\&.Ports\&.Native\&.Windows\&.CommOverlappedIo\&.Start (\fBSerialBuffer\fP buffer, string name)"

.PP
Start the I/O thread\&. 
.SH "Property Documentation"
.PP 
.SS "int RJCP\&.IO\&.Ports\&.Native\&.Windows\&.CommOverlappedIo\&.BytesToRead\fC [get]\fP"

.PP
Gets the number of bytes in the driver queue still to be read\&. The bytes to read\&. 
.SS "int RJCP\&.IO\&.Ports\&.Native\&.Windows\&.CommOverlappedIo\&.BytesToWrite\fC [get]\fP"

.PP
Gets the number bytes to of data in the transmit buffer\&. The number of bytes in the transmit buffer\&. 
.SS "bool RJCP\&.IO\&.Ports\&.Native\&.Windows\&.CommOverlappedIo\&.IsRunning\fC [get]\fP"

.PP
Test if the I/O thread is running\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for BSL430\&.NET from the source code\&.
