.TH "RJCP.IO.Ports.Native.ISerialBufferStreamData" 3 "Sat Jun 22 2019" "Version 1.2.1" "BSL430.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RJCP.IO.Ports.Native.ISerialBufferStreamData \- Container structure for properties and methods related to the Stream object\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBRJCP\&.IO\&.Ports\&.Native\&.SerialBuffer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBWaitForRead\fP (int timeout)"
.br
.RI "Waits up to a specified time out for data to be available to read\&. "
.ti -1c
.RI "bool \fBWaitForRead\fP (int count, int timeout)"
.br
.RI "Waits up to a specified time out for data to be available to read\&. "
.ti -1c
.RI "int \fBRead\fP (byte[] buffer, int offset, int count)"
.br
.RI "Reads data received by the Serial object, copying it into a buffer and reducing the read buffer size\&. "
.ti -1c
.RI "void \fBReadConsume\fP (int count)"
.br
.RI "Consume bytes from the incoming buffer\&. "
.ti -1c
.RI "int \fBRead\fP (char[] buffer, int offset, int count, Decoder decoder)"
.br
.RI "Reads data received by the serial object, converted to characters using the specified decoder\&. "
.ti -1c
.RI "int \fBReadByte\fP ()"
.br
.RI "Reads a single byte from the input queue\&. "
.ti -1c
.RI "void \fBDiscardInBuffer\fP ()"
.br
.RI "Discards data from the receive buffer\&. "
.ti -1c
.RI "bool \fBWaitForWrite\fP (int count, int timeout)"
.br
.RI "Waits up to a specified time out for enough data to be free in the write buffer\&. "
.ti -1c
.RI "void \fBAbortWait\fP ()"
.br
.RI "Aborts the wait for write\&. "
.ti -1c
.RI "int \fBWrite\fP (byte[] buffer, int offset, int count)"
.br
.RI "Puts data into the write buffer for the Serial object to send\&. "
.ti -1c
.RI "bool \fBFlush\fP (int timeout)"
.br
.RI "Waits for all data in the write buffer to be written with notification also by the serial buffer\&. "
.ti -1c
.RI "void \fBReset\fP (bool clearBuffer)"
.br
.RI "Reset the buffer to an initial state ready for a new connection\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBBytesToRead\fP\fC [get]\fP"
.br
.RI "Gets the number of bytes in the internal read buffer only\&. "
.ti -1c
.RI "int \fBBytesToWrite\fP\fC [get]\fP"
.br
.RI "Gets the number of bytes in the internal write buffer only\&. "
.in -1c
.SH "Detailed Description"
.PP 
Container structure for properties and methods related to the Stream object\&. 


.SH "Member Function Documentation"
.PP 
.SS "void RJCP\&.IO\&.Ports\&.Native\&.ISerialBufferStreamData\&.AbortWait ()"

.PP
Aborts the wait for write\&. 
.SS "void RJCP\&.IO\&.Ports\&.Native\&.ISerialBufferStreamData\&.DiscardInBuffer ()"

.PP
Discards data from the receive buffer\&. 
.SS "bool RJCP\&.IO\&.Ports\&.Native\&.ISerialBufferStreamData\&.Flush (int timeout)"

.PP
Waits for all data in the write buffer to be written with notification also by the serial buffer\&. 
.PP
\fBParameters:\fP
.RS 4
\fItimeout\fP The time out in milliseconds\&.
.RE
.PP
\fBReturns:\fP
.RS 4
\fCtrue\fP if the data was flushed within the specified time out; \fCfalse\fP otherwise\&.
.RE
.PP

.SS "int RJCP\&.IO\&.Ports\&.Native\&.ISerialBufferStreamData\&.Read (byte [] buffer, int offset, int count)"

.PP
Reads data received by the Serial object, copying it into a buffer and reducing the read buffer size\&. 
.PP
\fBParameters:\fP
.RS 4
\fIbuffer\fP The buffer to copy data into\&.
.br
\fIoffset\fP The offset where to copy data into\&.\&.
.br
\fIcount\fP The number of bytes to copy\&.
.RE
.PP
\fBReturns:\fP
.RS 4
Number of bytes actually read from the queue\&.
.RE
.PP

.SS "int RJCP\&.IO\&.Ports\&.Native\&.ISerialBufferStreamData\&.Read (char [] buffer, int offset, int count, Decoder decoder)"

.PP
Reads data received by the serial object, converted to characters using the specified decoder\&. 
.PP
\fBParameters:\fP
.RS 4
\fIbuffer\fP The character buffer to read into\&.
.br
\fIoffset\fP The offset into \fIbuffer\fP \&.
.br
\fIcount\fP The number of characters to write into \fIbuffer\fP \&.
.br
\fIdecoder\fP The decoder to use for the conversion\&.
.RE
.PP
\fBReturns:\fP
.RS 4
The number of characters read\&.
.RE
.PP
.PP
This method has no input checks that it is internal 
.SS "int RJCP\&.IO\&.Ports\&.Native\&.ISerialBufferStreamData\&.ReadByte ()"

.PP
Reads a single byte from the input queue\&. 
.PP
\fBReturns:\fP
.RS 4
The byte, cast to an Int32, or -1 if the end of the stream has been read\&.
.RE
.PP

.SS "void RJCP\&.IO\&.Ports\&.Native\&.ISerialBufferStreamData\&.ReadConsume (int count)"

.PP
Consume bytes from the incoming buffer\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcount\fP The number of bytes to discard at the beginning of the read byte buffer\&.
.RE
.PP

.SS "void RJCP\&.IO\&.Ports\&.Native\&.ISerialBufferStreamData\&.Reset (bool clearBuffer)"

.PP
Reset the buffer to an initial state ready for a new connection\&. 
.PP
\fBParameters:\fP
.RS 4
\fIclearBuffer\fP Set to \fCtrue\fP to reset the contents of the buffers\&.
.RE
.PP
.PP
This should only be closed when the serial port is closed\&. 
.SS "bool RJCP\&.IO\&.Ports\&.Native\&.ISerialBufferStreamData\&.WaitForRead (int timeout)"

.PP
Waits up to a specified time out for data to be available to read\&. 
.PP
\fBParameters:\fP
.RS 4
\fItimeout\fP The time out in milliseconds\&.
.RE
.PP
\fBReturns:\fP
.RS 4
\fCtrue\fP if data is available to read in time; \fCfalse\fP otherwise\&.
.RE
.PP

.SS "bool RJCP\&.IO\&.Ports\&.Native\&.ISerialBufferStreamData\&.WaitForRead (int count, int timeout)"

.PP
Waits up to a specified time out for data to be available to read\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcount\fP The number of bytes that should be in the read buffer\&.
.br
\fItimeout\fP The time out in milliseconds\&.
.RE
.PP
\fBReturns:\fP
.RS 4
\fCtrue\fP if data is available to read in time; \fCfalse\fP otherwise\&.
.RE
.PP

.SS "bool RJCP\&.IO\&.Ports\&.Native\&.ISerialBufferStreamData\&.WaitForWrite (int count, int timeout)"

.PP
Waits up to a specified time out for enough data to be free in the write buffer\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcount\fP The number of bytes required to be free\&.
.br
\fItimeout\fP The time out in milliseconds\&.
.RE
.PP
\fBReturns:\fP
.RS 4
\fCtrue\fP if \fIcount\fP  bytes are available for writing to the buffer; \fCfalse\fP if there is not enough buffer available within the \fItimeout\fP  parameter\&. If \fIcount\fP  is larger than the capacity of the buffer, \fCfalse\fP is returned immediately\&.
.RE
.PP

.SS "int RJCP\&.IO\&.Ports\&.Native\&.ISerialBufferStreamData\&.Write (byte [] buffer, int offset, int count)"

.PP
Puts data into the write buffer for the Serial object to send\&. 
.PP
\fBParameters:\fP
.RS 4
\fIbuffer\fP The buffer to copy data from\&.
.br
\fIoffset\fP The offset where to copy the data from\&.
.br
\fIcount\fP The number of bytes to copy\&.
.RE
.PP
\fBReturns:\fP
.RS 4
Number of bytes actually written to the queue\&.
.RE
.PP

.SH "Property Documentation"
.PP 
.SS "int RJCP\&.IO\&.Ports\&.Native\&.ISerialBufferStreamData\&.BytesToRead\fC [get]\fP"

.PP
Gets the number of bytes in the internal read buffer only\&. This value is independent of the actual number of bytes in the serial port hardware buffer\&. It will only return that which is currently obtained by the I/O thread\&. 
.SS "int RJCP\&.IO\&.Ports\&.Native\&.ISerialBufferStreamData\&.BytesToWrite\fC [get]\fP"

.PP
Gets the number of bytes in the internal write buffer only\&. This value is independent of the actual number of bytes in the serial port hardware buffer\&. It will only return that which is currently not completely written by the I/O thread\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for BSL430\&.NET from the source code\&.
