.TH "BSL430_NET.Comm" 3 "Tue Sep 17 2019" "Version 1.3.4" "BSL430.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BSL430_NET.Comm
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCommFTD2XX\fP"
.br
.ti -1c
.RI "class \fBCommLibftdi\fP"
.br
.ti -1c
.RI "class \fBCommSerial\fP"
.br
.ti -1c
.RI "class \fBCommUSB\fP"
.br
.ti -1c
.RI "class \fBFTDI_Device\fP"
.br
.RI "FTDI Device node extends generic \fBBsl430NetDevice\fP\&. Use requires D2XX library (FTD2XX\&.dll or libftd2xx\&.so) and driver installed (ftdibus\&.sys)\&. "
.ti -1c
.RI "class \fBLibftdi_Device\fP"
.br
.RI "Libftdi Device node extends generic \fBBsl430NetDevice\fP\&. Use requires libraries: libftdi, libusb, LibUsbDotNet "
.ti -1c
.RI "class \fBSerial_Device\fP"
.br
.RI "Serial Device node extends generic \fBBsl430NetDevice\fP\&. Use requires library: SerialPortStream\&. NOTE: If target app use \&.NET Framework 4\&.6\&.2 or lower, Nuget package: Microsoft\&.Win32\&.Registry is required! "
.ti -1c
.RI "class \fBUSB_HID_Device\fP"
.br
.RI "USB HID Device node extends generic \fBBsl430NetDevice\fP\&. Use requires libraries: HidSharp\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BSL430\&.NET from the source code\&.
