.TH "BSL430_NET.ScanResult< Tdev >" 3 "Tue Sep 17 2019" "Version 1.3.4" "BSL430.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BSL430_NET.ScanResult< Tdev > \- Scan Result wraps \fBStatus\fP and List of Devices - \fBBsl430NetDevice\fP childs (FTDI / Libftdi / Serial / USB)\&.  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBStatus\fP \fBStatus\fP\fC [get, set]\fP"
.br
.RI "Scan \fBStatus\fP is result of each device scan, any error with corresponding number and message will be set\&. "
.ti -1c
.RI "List< Tdev > \fBDevices\fP\fC [get, set]\fP"
.br
.RI "List of Devices - \fBBsl430NetDevice\fP childs\&. This is main device container, used as input to any operation\&. "
.in -1c
.SH "Detailed Description"
.PP 
Scan Result wraps \fBStatus\fP and List of Devices - \fBBsl430NetDevice\fP childs (FTDI / Libftdi / Serial / USB)\&. 


.PP
\fBType Constraints\fP
.TP
\fITdev\fP : \fI\fBBsl430NetDevice\fP\fP
.SH "Property Documentation"
.PP 
.SS "List<Tdev> \fBBSL430_NET\&.ScanResult\fP< Tdev >\&.Devices\fC [get]\fP, \fC [set]\fP"

.PP
List of Devices - \fBBsl430NetDevice\fP childs\&. This is main device container, used as input to any operation\&. 
.SS "\fBStatus\fP \fBBSL430_NET\&.ScanResult\fP< Tdev >\&.\fBStatus\fP\fC [get]\fP, \fC [set]\fP"

.PP
Scan \fBStatus\fP is result of each device scan, any error with corresponding number and message will be set\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for BSL430\&.NET from the source code\&.
