.TH "BSL430_NET.FirmwareTools.FwTools.BslPasswords" 3 "Tue Sep 17 2019" "Version 1.3.4" "BSL430.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BSL430_NET.FirmwareTools.FwTools.BslPasswords \- [MSP430 specific] BSL Password is required for almost any BSL operation except Mass Erase\&. Password is last 16-byte (F543x-non-A only) or 32-byte (others) of IVT (FFE0-FFFF), if newer 5xx/6xx MCU is used\&. If MCU from older series is used (1xx/2xx/4xx), password is exactly 20-byte long\&. Mostly it is 32-byte\&.  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "byte[] \fBPassword32Byte\fP\fC [get, set]\fP"
.br
.RI "This is the password mostly used in todays MSP430 MCUs, 5xx/6xx series except F543x (non A)\&. "
.ti -1c
.RI "byte[] \fBPassword16Byte\fP\fC [get, set]\fP"
.br
.RI "16-byte long Password used only in the very first series of 5xx, the F543x (non A)\&. "
.ti -1c
.RI "byte[] \fBPassword20Byte\fP\fC [get, set]\fP"
.br
.RI "20-byte long Password used in old 1xx/2xx/4xx series\&. "
.in -1c
.SH "Detailed Description"
.PP 
[MSP430 specific] BSL Password is required for almost any BSL operation except Mass Erase\&. Password is last 16-byte (F543x-non-A only) or 32-byte (others) of IVT (FFE0-FFFF), if newer 5xx/6xx MCU is used\&. If MCU from older series is used (1xx/2xx/4xx), password is exactly 20-byte long\&. Mostly it is 32-byte\&. 


.SH "Property Documentation"
.PP 
.SS "byte [] BSL430_NET\&.FirmwareTools\&.FwTools\&.BslPasswords\&.Password16Byte\fC [get]\fP, \fC [set]\fP"

.PP
16-byte long Password used only in the very first series of 5xx, the F543x (non A)\&. 
.SS "byte [] BSL430_NET\&.FirmwareTools\&.FwTools\&.BslPasswords\&.Password20Byte\fC [get]\fP, \fC [set]\fP"

.PP
20-byte long Password used in old 1xx/2xx/4xx series\&. 
.SS "byte [] BSL430_NET\&.FirmwareTools\&.FwTools\&.BslPasswords\&.Password32Byte\fC [get]\fP, \fC [set]\fP"

.PP
This is the password mostly used in todays MSP430 MCUs, 5xx/6xx series except F543x (non A)\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for BSL430\&.NET from the source code\&.
