.TH "BSL430_NET.FirmwareTools.Helpers" 3 "Tue Sep 17 2019" "Version 1.3.4" "BSL430.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BSL430_NET.FirmwareTools.Helpers
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFirmwareToolsException\fP"
.br
.RI "Firmware Tools Exception is generic Exception extended with Error and Msg (status) objects\&. "
.ti -1c
.RI "class \fBFwNodeAddrComparer\fP"
.br
.RI "Compares Firmware Node addresses only\&. Useful when searching for fw addr overlap between two files\&. "
.ti -1c
.RI "class \fBFwNodeComparer\fP"
.br
.RI "Compares whole Firmware Node, address and data\&. Useful when comparing two firmware files\&. "
.ti -1c
.RI "class \fBHelpers\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BSL430\&.NET from the source code\&.
