.TH "BSL430_NET.Bsl430NetDevice" 3 "Tue Sep 17 2019" "Version 1.3.4" "BSL430.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BSL430_NET.Bsl430NetDevice \- BSL430\&.NET Device node serve as a generic device indentificator with field 'Name' as a key\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBBSL430_NET\&.Comm\&.FTDI_Device\fP, \fBBSL430_NET\&.Comm\&.Libftdi_Device\fP, \fBBSL430_NET\&.Comm\&.Serial_Device\fP, and \fBBSL430_NET\&.Comm\&.USB_HID_Device\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBsl430NetDevice\fP ()"
.br
.RI "\fBBsl430NetDevice\fP constructor "
.ti -1c
.RI "\fBBsl430NetDevice\fP (\fBBsl430NetDevice\fP Dev)"
.br
.RI "\fBBsl430NetDevice\fP copy constructor "
.ti -1c
.RI "\fBBsl430NetDevice\fP (string DeviceName)"
.br
.RI "\fBBsl430NetDevice\fP constructor "
.ti -1c
.RI "\fBBsl430NetDevice\fP (string DeviceName, string \fBDescription\fP, string FullDesc, \fBMode\fP \fBMode\fP, string \fBKind\fP)"
.br
.RI "\fBBsl430NetDevice\fP constructor "
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.RI "FormattedDescription of current device\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBName\fP = ''\fC [get, set]\fP"
.br
.RI "Name is unique string that serves as main key to handle devices in this library eg\&. COM1, FTDI2, libtfi3, USB4 \&.\&. "
.ti -1c
.RI "string \fBDescription\fP = ''\fC [get, set]\fP"
.br
.RI "Device description\&. "
.ti -1c
.RI "string \fBKind\fP = ''\fC [get, set]\fP"
.br
.RI "Device kind\&. [FTDI, libftdi, COM (Serial), USB] "
.ti -1c
.RI "string \fBFormattedDescription\fP = ''\fC [get, set]\fP"
.br
.RI "Device general formated description eg\&. 'V/PID: 1234-5678 [Dev1] SN: 0123456' "
.ti -1c
.RI "\fBMode\fP \fBMode\fP = \fBMode\&.UART_Serial\fP\fC [get, set]\fP"
.br
.RI "Device mode\&. "
.in -1c
.SH "Detailed Description"
.PP 
BSL430\&.NET Device node serve as a generic device indentificator with field 'Name' as a key\&. 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "BSL430_NET\&.Bsl430NetDevice\&.Bsl430NetDevice ()"

.PP
\fBBsl430NetDevice\fP constructor 
.SS "BSL430_NET\&.Bsl430NetDevice\&.Bsl430NetDevice (\fBBsl430NetDevice\fP Dev)"

.PP
\fBBsl430NetDevice\fP copy constructor 
.SS "BSL430_NET\&.Bsl430NetDevice\&.Bsl430NetDevice (string DeviceName)"

.PP
\fBBsl430NetDevice\fP constructor 
.SS "BSL430_NET\&.Bsl430NetDevice\&.Bsl430NetDevice (string DeviceName, string Description, string FullDesc, \fBMode\fP Mode, string Kind)"

.PP
\fBBsl430NetDevice\fP constructor 
.SH "Member Function Documentation"
.PP 
.SS "override string BSL430_NET\&.Bsl430NetDevice\&.ToString ()"

.PP
FormattedDescription of current device\&. 
.SH "Property Documentation"
.PP 
.SS "string BSL430_NET\&.Bsl430NetDevice\&.Description = ''\fC [get]\fP, \fC [set]\fP"

.PP
Device description\&. 
.SS "string BSL430_NET\&.Bsl430NetDevice\&.FormattedDescription = ''\fC [get]\fP, \fC [set]\fP"

.PP
Device general formated description eg\&. 'V/PID: 1234-5678 [Dev1] SN: 0123456' 
.SS "string BSL430_NET\&.Bsl430NetDevice\&.Kind = ''\fC [get]\fP, \fC [set]\fP"

.PP
Device kind\&. [FTDI, libftdi, COM (Serial), USB] 
.SS "\fBMode\fP BSL430_NET\&.Bsl430NetDevice\&.Mode = \fBMode\&.UART_Serial\fP\fC [get]\fP, \fC [set]\fP"

.PP
Device mode\&. 
.SS "string BSL430_NET\&.Bsl430NetDevice\&.Name = ''\fC [get]\fP, \fC [set]\fP"

.PP
Name is unique string that serves as main key to handle devices in this library eg\&. COM1, FTDI2, libtfi3, USB4 \&.\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for BSL430\&.NET from the source code\&.
