.TH "BSL430_NET.FirmwareTools" 3 "Tue Sep 17 2019" "Version 1.3.4" "BSL430.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BSL430_NET.FirmwareTools
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBExtensions\fP"
.br
.RI "\fBExtensions\fP class wrapping some extensions methods like CRC calc, ToByteArray or ToExt\&. "
.ti -1c
.RI "class \fBFwTools\fP"
.br
.RI "\fBFwTools\fP class provides basic manipulation (Parse, Create, Convert, Combine, Validate, Compare) with Intel-HEX, TI-TXT, SREC and ELF firmware formatted files\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BSL430\&.NET from the source code\&.
