.TH "BSL430_NET.Bsl430NetException" 3 "Tue Sep 17 2019" "Version 1.3.4" "BSL430.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BSL430_NET.Bsl430NetException \- BSL430\&.NET Exception is generic Exception extended with \fBStatus\fP object\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBsl430NetException\fP (string Message)"
.br
.RI "\fBBsl430NetException\fP constructor "
.ti -1c
.RI "\fBBsl430NetException\fP (\fBStatus\fP Stat)"
.br
.RI "\fBBsl430NetException\fP constructor "
.ti -1c
.RI "\fBBsl430NetException\fP (int ErrCode)"
.br
.RI "\fBBsl430NetException\fP constructor "
.ti -1c
.RI "\fBBsl430NetException\fP (int ErrCode, Exception Ex)"
.br
.RI "\fBBsl430NetException\fP constructor "
.ti -1c
.RI "\fBBsl430NetException\fP (int ErrCode, string Extra)"
.br
.RI "\fBBsl430NetException\fP constructor "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBStatus\fP \fBStatus\fP\fC [get, set]\fP"
.br
.RI "BSL430\&.NET \fBStatus\fP "
.in -1c
.SH "Detailed Description"
.PP 
BSL430\&.NET Exception is generic Exception extended with \fBStatus\fP object\&. 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "BSL430_NET\&.Bsl430NetException\&.Bsl430NetException (string Message)"

.PP
\fBBsl430NetException\fP constructor 
.SS "BSL430_NET\&.Bsl430NetException\&.Bsl430NetException (\fBStatus\fP Stat)"

.PP
\fBBsl430NetException\fP constructor 
.SS "BSL430_NET\&.Bsl430NetException\&.Bsl430NetException (int ErrCode)"

.PP
\fBBsl430NetException\fP constructor 
.SS "BSL430_NET\&.Bsl430NetException\&.Bsl430NetException (int ErrCode, Exception Ex)"

.PP
\fBBsl430NetException\fP constructor 
.SS "BSL430_NET\&.Bsl430NetException\&.Bsl430NetException (int ErrCode, string Extra)"

.PP
\fBBsl430NetException\fP constructor 
.SH "Property Documentation"
.PP 
.SS "\fBStatus\fP BSL430_NET\&.Bsl430NetException\&.Status\fC [get]\fP, \fC [set]\fP"

.PP
BSL430\&.NET \fBStatus\fP 

.SH "Author"
.PP 
Generated automatically by Doxygen for BSL430\&.NET from the source code\&.
