.TH "BSL430_NET.Main.Core" 3 "Tue Sep 17 2019" "Version 1.3.4" "BSL430.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BSL430_NET.Main.Core
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBBSL430_NET\&.Main\&.IDevice\fP, \fBBSL430_NET\&.Main\&.ICommable\fP, \fBBSL430_NET\&.Main\&.IDevice\fP, and \fBBSL430_NET\&.Main\&.ICommable\fP\&.
.PP
Inherited by \fBBSL430_NET\&.Comm\&.CommFTD2XX\fP, \fBBSL430_NET\&.Comm\&.CommLibftdi\fP, \fBBSL430_NET\&.Comm\&.CommSerial\fP, and \fBBSL430_NET\&.Comm\&.CommUSB\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCmdStat\fP"
.br
.ti -1c
.RI "class \fBData_BSLVersion\fP"
.br
.ti -1c
.RI "class \fBData_CRC\fP"
.br
.ti -1c
.RI "class \fBData_Download\fP"
.br
.ti -1c
.RI "class \fBData_Void\fP"
.br
.ti -1c
.RI "interface \fBIData\fP"
.br
.ti -1c
.RI "class \fBMessage\fP"
.br
.ti -1c
.RI "class \fBResponse\fP"
.br
.ti -1c
.RI "class \fBResult\fP"
.br
.ti -1c
.RI "class \fBRx_Block\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "abstract void \fBCommOpen\fP (\fBBsl430NetDevice\fP device)"
.br
.ti -1c
.RI "abstract void \fBCommSet\fP (\fBBaudRate\fP baud_rate)"
.br
.ti -1c
.RI "abstract void \fBCommDtr\fP (bool val=true, bool ignore_err=false)"
.br
.ti -1c
.RI "abstract void \fBCommRts\fP (bool val=true, bool ignore_err=false)"
.br
.ti -1c
.RI "abstract void \fBCommClrBuff\fP ()"
.br
.ti -1c
.RI "abstract void \fBCommClose\fP (bool ignore_err=false)"
.br
.ti -1c
.RI "abstract \fBBsl430NetDevice\fP \fBCommGetDefaultDevice\fP ()"
.br
.ti -1c
.RI "abstract \fBStatus\fP \fBCommXfer\fP (out byte[] msg_rx, byte[] msg_tx, int rx_size)"
.br
.ti -1c
.RI "abstract \fBStatus\fP \fBScan< Tdev >\fP (out List< Tdev > device_list, \fBScanOptions\fP scan_opt=\fBScanOptions\&.None\fP)"
.br
.ti -1c
.RI "\fBBaudRate\fP \fBGetBaudRate\fP ()"
.br
.ti -1c
.RI "\fBInvokeMechanism\fP \fBGetInvoke\fP ()"
.br
.ti -1c
.RI "\fBMCU\fP \fBGetMCU\fP ()"
.br
.ti -1c
.RI "\fBCore\fP (\fBBSL430NET\fP _root, \fBMode\fP _mode)"
.br
.ti -1c
.RI "\fBStatusEx\fP \fBErase\fP (\fBBsl430NetDevice\fP device)"
.br
.ti -1c
.RI "\fBStatusEx\fP \fBDownload\fP (\fBBsl430NetDevice\fP device, byte[] password, int addr_start, int data_size, out List< byte > data)"
.br
.ti -1c
.RI "\fBStatusEx\fP \fBUpload\fP (\fBBsl430NetDevice\fP device, string firmware_path, byte[] password)"
.br
.ti -1c
.RI "\fBStatus\fP \fBChangeBaudRate\fP (\fBBaudRate\fP _baud)"
.br
.ti -1c
.RI "\fBStatus\fP \fBSetInvoke\fP (\fBInvokeMechanism\fP _invoke)"
.br
.ti -1c
.RI "\fBStatus\fP \fBSetMCU\fP (\fBMCU\fP _mcu)"
.br
.ti -1c
.RI "void \fBDispose\fP ()"
.br
.in -1c
.SS "Package Types"

.in +1c
.ti -1c
.RI "enum \fBCommand\fP { \fBBaudRate\fP, \fBBSLVersion\fP, \fBMassErase\fP, \fBCRC\fP, \fBPassword\fP, \fBUpload\fP, \fBDownload\fP, \fBLoadPC\fP }"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "abstract \fBBsl430NetDevice\fP \fBDefaultDevice\fP\fC [get, set]\fP"
.br
.in -1c
.SS "Private Types"

.in +1c
.ti -1c
.RI "enum \fBProtocol\fP { \fBUART_1_2_4\fP = 250, \fBUART_5_6\fP = 260, \fBUSB_5_6\fP = 62 }"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBStatusEx\fP \fBLoadEx\fP (\fBBsl430NetDevice\fP device, Command cmd, byte[] password, string firmware_path, int? addr_start, int? data_size, out List< byte > output)"
.br
.ti -1c
.RI "void \fBBlockStart\fP (string name, double val, bool _skipped=false)"
.br
.ti -1c
.RI "void \fBBlockEnd\fP (\fBReportResult\fP result, string name_override='')"
.br
.ti -1c
.RI "void \fBBlockEnd\fP (string name_override='')"
.br
.ti -1c
.RI "void \fBUpdateProgress\fP (double val, string str)"
.br
.ti -1c
.RI "void \fBUpdateProgress\fP (double val, \fBReport\fP _report, bool add_report)"
.br
.ti -1c
.RI "void \fBDispose\fP (bool disposing)"
.br
.ti -1c
.RI "\fBMessage\fP \fBBuildMsg\fP (Command command)"
.br
.ti -1c
.RI "\fBMessage\fP \fBBuildMsg\fP (Command command, int? address)"
.br
.ti -1c
.RI "\fBMessage\fP \fBBuildMsg\fP (Command command, byte[] data)"
.br
.ti -1c
.RI "\fBMessage\fP \fBBuildMsg\fP (Command command, int? address, byte[] data)"
.br
.ti -1c
.RI "\fBResponse\fP \fBProcessMsg\fP (\fBMessage\fP message)"
.br
.ti -1c
.RI "\fBResult\fP< T > \fBParseResp< T >\fP (\fBResponse\fP answer)"
.br
.ti -1c
.RI "\fBStatus\fP \fBParseFirmware\fP (string firmware_path, out List< \fBRx_Block\fP > rx_blocks, out \fBFwTools\&.FwInfo\fP fw_info)"
.br
.ti -1c
.RI "int \fBGetBufferSize\fP (Protocol _protocol)"
.br
.ti -1c
.RI "void \fBInvokeBSL\fP (\fBInvokeMechanism\fP mech)"
.br
.ti -1c
.RI "void \fBResetMCU\fP (\fBInvokeMechanism\fP mech)"
.br
.ti -1c
.RI "byte[] \fBValidatePassword\fP (byte[] password, out bool pw_overide)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBBaudRate\fP \fBbaud_rate\fP = \fBBaudRate\&.BAUD_115200\fP"
.br
.ti -1c
.RI "\fBMCU\fP \fBmcu\fP = \fBMCU\&.MSP430_F5xx\fP"
.br
.ti -1c
.RI "Protocol \fBprotocol\fP = Protocol\&.UART_5_6"
.br
.ti -1c
.RI "\fBInvokeMechanism\fP \fBinvoke\fP = \fBInvokeMechanism\&.SHARED_JTAG\fP"
.br
.ti -1c
.RI "\fBReport\fP \fBreport\fP"
.br
.ti -1c
.RI "readonly List< \fBReport\fP > \fBreports\fP = new List<\fBReport\fP>()"
.br
.ti -1c
.RI "readonly \fBBSL430NET\fP \fBroot\fP"
.br
.ti -1c
.RI "readonly \fBMode\fP \fBmode\fP"
.br
.ti -1c
.RI "bool \fBskipped\fP"
.br
.ti -1c
.RI "bool \fBblock_pending\fP"
.br
.ti -1c
.RI "double \fBprogress_pending\fP"
.br
.ti -1c
.RI "bool \fBdisposedValue\fP = false"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for BSL430\&.NET from the source code\&.
