.TH "FTD2XX_NET.FTDI.FT_FLOW_CONTROL" 3 "Sat Jun 22 2019" "Version 1.2.1" "BSL430.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FTD2XX_NET.FTDI.FT_FLOW_CONTROL \- Permitted flow control values for \fBFTDI\fP devices  

.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const UInt16 \fBFT_FLOW_NONE\fP = 0x0000"
.br
.RI "No flow control "
.ti -1c
.RI "const UInt16 \fBFT_FLOW_RTS_CTS\fP = 0x0100"
.br
.RI "RTS/CTS flow control "
.ti -1c
.RI "const UInt16 \fBFT_FLOW_DTR_DSR\fP = 0x0200"
.br
.RI "DTR/DSR flow control "
.ti -1c
.RI "const UInt16 \fBFT_FLOW_XON_XOFF\fP = 0x0400"
.br
.RI "Xon/Xoff flow control "
.in -1c
.SH "Detailed Description"
.PP 
Permitted flow control values for \fBFTDI\fP devices 


.SH "Member Data Documentation"
.PP 
.SS "const UInt16 FTD2XX_NET\&.FTDI\&.FT_FLOW_CONTROL\&.FT_FLOW_DTR_DSR = 0x0200"

.PP
DTR/DSR flow control 
.SS "const UInt16 FTD2XX_NET\&.FTDI\&.FT_FLOW_CONTROL\&.FT_FLOW_NONE = 0x0000"

.PP
No flow control 
.SS "const UInt16 FTD2XX_NET\&.FTDI\&.FT_FLOW_CONTROL\&.FT_FLOW_RTS_CTS = 0x0100"

.PP
RTS/CTS flow control 
.SS "const UInt16 FTD2XX_NET\&.FTDI\&.FT_FLOW_CONTROL\&.FT_FLOW_XON_XOFF = 0x0400"

.PP
Xon/Xoff flow control 

.SH "Author"
.PP 
Generated automatically by Doxygen for BSL430\&.NET from the source code\&.
