.TH "FTD2XX_NET.FTDI.FT2232_EEPROM_STRUCTURE" 3 "Sat Jun 22 2019" "Version 1.2.1" "BSL430.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FTD2XX_NET.FTDI.FT2232_EEPROM_STRUCTURE \- EEPROM structure specific to FT2232 devices\&. Inherits from \fBFT_EEPROM_DATA\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFTD2XX_NET\&.FTDI\&.FT_EEPROM_DATA\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBPullDownEnable\fP = false"
.br
.RI "Determines if IOs are pulled down when the device is in suspend "
.ti -1c
.RI "bool \fBSerNumEnable\fP = true"
.br
.RI "Determines if the serial number is enabled "
.ti -1c
.RI "bool \fBUSBVersionEnable\fP = true"
.br
.RI "Determines if the USB version number is enabled "
.ti -1c
.RI "UInt16 \fBUSBVersion\fP = 0x0200"
.br
.RI "The USB version number\&. Should be either 0x0110 (USB 1\&.1) or 0x0200 (USB 2\&.0) "
.ti -1c
.RI "bool \fBAIsHighCurrent\fP = false"
.br
.RI "Enables high current IOs on channel A "
.ti -1c
.RI "bool \fBBIsHighCurrent\fP = false"
.br
.RI "Enables high current IOs on channel B "
.ti -1c
.RI "bool \fBIFAIsFifo\fP = false"
.br
.RI "Determines if channel A is in FIFO mode "
.ti -1c
.RI "bool \fBIFAIsFifoTar\fP = false"
.br
.RI "Determines if channel A is in FIFO target mode "
.ti -1c
.RI "bool \fBIFAIsFastSer\fP = false"
.br
.RI "Determines if channel A is in fast serial mode "
.ti -1c
.RI "bool \fBAIsVCP\fP = true"
.br
.RI "Determines if channel A loads the VCP driver "
.ti -1c
.RI "bool \fBIFBIsFifo\fP = false"
.br
.RI "Determines if channel B is in FIFO mode "
.ti -1c
.RI "bool \fBIFBIsFifoTar\fP = false"
.br
.RI "Determines if channel B is in FIFO target mode "
.ti -1c
.RI "bool \fBIFBIsFastSer\fP = false"
.br
.RI "Determines if channel B is in fast serial mode "
.ti -1c
.RI "bool \fBBIsVCP\fP = true"
.br
.RI "Determines if channel B loads the VCP driver "
.in -1c
.SH "Detailed Description"
.PP 
EEPROM structure specific to FT2232 devices\&. Inherits from \fBFT_EEPROM_DATA\fP\&. 


.SH "Member Data Documentation"
.PP 
.SS "bool FTD2XX_NET\&.FTDI\&.FT2232_EEPROM_STRUCTURE\&.AIsHighCurrent = false"

.PP
Enables high current IOs on channel A 
.SS "bool FTD2XX_NET\&.FTDI\&.FT2232_EEPROM_STRUCTURE\&.AIsVCP = true"

.PP
Determines if channel A loads the VCP driver 
.SS "bool FTD2XX_NET\&.FTDI\&.FT2232_EEPROM_STRUCTURE\&.BIsHighCurrent = false"

.PP
Enables high current IOs on channel B 
.SS "bool FTD2XX_NET\&.FTDI\&.FT2232_EEPROM_STRUCTURE\&.BIsVCP = true"

.PP
Determines if channel B loads the VCP driver 
.SS "bool FTD2XX_NET\&.FTDI\&.FT2232_EEPROM_STRUCTURE\&.IFAIsFastSer = false"

.PP
Determines if channel A is in fast serial mode 
.SS "bool FTD2XX_NET\&.FTDI\&.FT2232_EEPROM_STRUCTURE\&.IFAIsFifo = false"

.PP
Determines if channel A is in FIFO mode 
.SS "bool FTD2XX_NET\&.FTDI\&.FT2232_EEPROM_STRUCTURE\&.IFAIsFifoTar = false"

.PP
Determines if channel A is in FIFO target mode 
.SS "bool FTD2XX_NET\&.FTDI\&.FT2232_EEPROM_STRUCTURE\&.IFBIsFastSer = false"

.PP
Determines if channel B is in fast serial mode 
.SS "bool FTD2XX_NET\&.FTDI\&.FT2232_EEPROM_STRUCTURE\&.IFBIsFifo = false"

.PP
Determines if channel B is in FIFO mode 
.SS "bool FTD2XX_NET\&.FTDI\&.FT2232_EEPROM_STRUCTURE\&.IFBIsFifoTar = false"

.PP
Determines if channel B is in FIFO target mode 
.SS "bool FTD2XX_NET\&.FTDI\&.FT2232_EEPROM_STRUCTURE\&.PullDownEnable = false"

.PP
Determines if IOs are pulled down when the device is in suspend 
.SS "bool FTD2XX_NET\&.FTDI\&.FT2232_EEPROM_STRUCTURE\&.SerNumEnable = true"

.PP
Determines if the serial number is enabled 
.SS "UInt16 FTD2XX_NET\&.FTDI\&.FT2232_EEPROM_STRUCTURE\&.USBVersion = 0x0200"

.PP
The USB version number\&. Should be either 0x0110 (USB 1\&.1) or 0x0200 (USB 2\&.0) 
.SS "bool FTD2XX_NET\&.FTDI\&.FT2232_EEPROM_STRUCTURE\&.USBVersionEnable = true"

.PP
Determines if the USB version number is enabled 

.SH "Author"
.PP 
Generated automatically by Doxygen for BSL430\&.NET from the source code\&.
