.TH "FTD2XX_NET.FTDI.FT_FLAGS" 3 "Sat Jun 22 2019" "Version 1.2.1" "BSL430.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FTD2XX_NET.FTDI.FT_FLAGS \- Flags that provide information on the \fBFTDI\fP device state  

.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const UInt32 \fBFT_FLAGS_OPENED\fP = 0x00000001"
.br
.RI "Indicates that the device is open "
.ti -1c
.RI "const UInt32 \fBFT_FLAGS_HISPEED\fP = 0x00000002"
.br
.RI "Indicates that the device is enumerated as a hi-speed USB device "
.in -1c
.SH "Detailed Description"
.PP 
Flags that provide information on the \fBFTDI\fP device state 


.SH "Member Data Documentation"
.PP 
.SS "const UInt32 FTD2XX_NET\&.FTDI\&.FT_FLAGS\&.FT_FLAGS_HISPEED = 0x00000002"

.PP
Indicates that the device is enumerated as a hi-speed USB device 
.SS "const UInt32 FTD2XX_NET\&.FTDI\&.FT_FLAGS\&.FT_FLAGS_OPENED = 0x00000001"

.PP
Indicates that the device is open 

.SH "Author"
.PP 
Generated automatically by Doxygen for BSL430\&.NET from the source code\&.
