.TH "FTD2XX_NET.FTDI.FT_EVENTS" 3 "Sat Jun 22 2019" "Version 1.2.1" "BSL430.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FTD2XX_NET.FTDI.FT_EVENTS \- \fBFTDI\fP device event types that can be monitored  

.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const UInt32 \fBFT_EVENT_RXCHAR\fP = 0x00000001"
.br
.RI "Event on receive character "
.ti -1c
.RI "const UInt32 \fBFT_EVENT_MODEM_STATUS\fP = 0x00000002"
.br
.RI "Event on modem status change "
.ti -1c
.RI "const UInt32 \fBFT_EVENT_LINE_STATUS\fP = 0x00000004"
.br
.RI "Event on line status change "
.in -1c
.SH "Detailed Description"
.PP 
\fBFTDI\fP device event types that can be monitored 


.SH "Member Data Documentation"
.PP 
.SS "const UInt32 FTD2XX_NET\&.FTDI\&.FT_EVENTS\&.FT_EVENT_LINE_STATUS = 0x00000004"

.PP
Event on line status change 
.SS "const UInt32 FTD2XX_NET\&.FTDI\&.FT_EVENTS\&.FT_EVENT_MODEM_STATUS = 0x00000002"

.PP
Event on modem status change 
.SS "const UInt32 FTD2XX_NET\&.FTDI\&.FT_EVENTS\&.FT_EVENT_RXCHAR = 0x00000001"

.PP
Event on receive character 

.SH "Author"
.PP 
Generated automatically by Doxygen for BSL430\&.NET from the source code\&.
