.TH "FTD2XX_NET.FTDI.FT_EXCEPTION" 3 "Sat Jun 22 2019" "Version 1.2.1" "BSL430.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FTD2XX_NET.FTDI.FT_EXCEPTION \- Exceptions thrown by errors within the \fBFTDI\fP class\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFT_EXCEPTION\fP ()"
.br
.ti -1c
.RI "\fBFT_EXCEPTION\fP (string message)"
.br
.ti -1c
.RI "\fBFT_EXCEPTION\fP (string message, Exception inner)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBFT_EXCEPTION\fP (System\&.Runtime\&.Serialization\&.SerializationInfo info, System\&.Runtime\&.Serialization\&.StreamingContext context)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Exceptions thrown by errors within the \fBFTDI\fP class\&. 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "FTD2XX_NET\&.FTDI\&.FT_EXCEPTION\&.FT_EXCEPTION ()"

.PP

.SS "FTD2XX_NET\&.FTDI\&.FT_EXCEPTION\&.FT_EXCEPTION (string message)"

.PP

.PP
\fBParameters:\fP
.RS 4
\fImessage\fP 
.RE
.PP

.SS "FTD2XX_NET\&.FTDI\&.FT_EXCEPTION\&.FT_EXCEPTION (string message, Exception inner)"

.PP

.PP
\fBParameters:\fP
.RS 4
\fImessage\fP 
.br
\fIinner\fP 
.RE
.PP

.SS "FTD2XX_NET\&.FTDI\&.FT_EXCEPTION\&.FT_EXCEPTION (System\&.Runtime\&.Serialization\&.SerializationInfo info, System\&.Runtime\&.Serialization\&.StreamingContext context)\fC [protected]\fP"

.PP

.PP
\fBParameters:\fP
.RS 4
\fIinfo\fP 
.br
\fIcontext\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for BSL430\&.NET from the source code\&.
