.TH "FTD2XX_NET.FTDI.FT_232H_CBUS_OPTIONS" 3 "Sat Jun 22 2019" "Version 1.2.1" "BSL430.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FTD2XX_NET.FTDI.FT_232H_CBUS_OPTIONS \- Available functions for the FT232H CBUS pins\&. Controlled by FT232H EEPROM settings  

.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const byte \fBFT_CBUS_TRISTATE\fP = 0x00"
.br
.RI "FT232H CBUS EEPROM options - Tristate "
.ti -1c
.RI "const byte \fBFT_CBUS_RXLED\fP = 0x01"
.br
.RI "FT232H CBUS EEPROM options - Rx LED "
.ti -1c
.RI "const byte \fBFT_CBUS_TXLED\fP = 0x02"
.br
.RI "FT232H CBUS EEPROM options - Tx LED "
.ti -1c
.RI "const byte \fBFT_CBUS_TXRXLED\fP = 0x03"
.br
.RI "FT232H CBUS EEPROM options - Tx and Rx LED "
.ti -1c
.RI "const byte \fBFT_CBUS_PWREN\fP = 0x04"
.br
.RI "FT232H CBUS EEPROM options - Power Enable# "
.ti -1c
.RI "const byte \fBFT_CBUS_SLEEP\fP = 0x05"
.br
.RI "FT232H CBUS EEPROM options - Sleep "
.ti -1c
.RI "const byte \fBFT_CBUS_DRIVE_0\fP = 0x06"
.br
.RI "FT232H CBUS EEPROM options - Drive pin to logic 0 "
.ti -1c
.RI "const byte \fBFT_CBUS_DRIVE_1\fP = 0x07"
.br
.RI "FT232H CBUS EEPROM options - Drive pin to logic 1 "
.ti -1c
.RI "const byte \fBFT_CBUS_IOMODE\fP = 0x08"
.br
.RI "FT232H CBUS EEPROM options - IO Mode "
.ti -1c
.RI "const byte \fBFT_CBUS_TXDEN\fP = 0x09"
.br
.RI "FT232H CBUS EEPROM options - Tx Data Enable "
.ti -1c
.RI "const byte \fBFT_CBUS_CLK30\fP = 0x0A"
.br
.RI "FT232H CBUS EEPROM options - 30MHz clock "
.ti -1c
.RI "const byte \fBFT_CBUS_CLK15\fP = 0x0B"
.br
.RI "FT232H CBUS EEPROM options - 15MHz clock "
.ti -1c
.RI "const byte \fBFT_CBUS_CLK7_5\fP = 0x0C"
.br
.in -1c
.SH "Detailed Description"
.PP 
Available functions for the FT232H CBUS pins\&. Controlled by FT232H EEPROM settings 


.SH "Member Data Documentation"
.PP 
.SS "const byte FTD2XX_NET\&.FTDI\&.FT_232H_CBUS_OPTIONS\&.FT_CBUS_CLK15 = 0x0B"

.PP
FT232H CBUS EEPROM options - 15MHz clock 
.SS "const byte FTD2XX_NET\&.FTDI\&.FT_232H_CBUS_OPTIONS\&.FT_CBUS_CLK30 = 0x0A"

.PP
FT232H CBUS EEPROM options - 30MHz clock 
.SS "const byte FTD2XX_NET\&.FTDI\&.FT_232H_CBUS_OPTIONS\&.FT_CBUS_CLK7_5 = 0x0C"

.PP
FT232H CBUS EEPROM options - 7\&.5MHz clock 
.SS "const byte FTD2XX_NET\&.FTDI\&.FT_232H_CBUS_OPTIONS\&.FT_CBUS_DRIVE_0 = 0x06"

.PP
FT232H CBUS EEPROM options - Drive pin to logic 0 
.SS "const byte FTD2XX_NET\&.FTDI\&.FT_232H_CBUS_OPTIONS\&.FT_CBUS_DRIVE_1 = 0x07"

.PP
FT232H CBUS EEPROM options - Drive pin to logic 1 
.SS "const byte FTD2XX_NET\&.FTDI\&.FT_232H_CBUS_OPTIONS\&.FT_CBUS_IOMODE = 0x08"

.PP
FT232H CBUS EEPROM options - IO Mode 
.SS "const byte FTD2XX_NET\&.FTDI\&.FT_232H_CBUS_OPTIONS\&.FT_CBUS_PWREN = 0x04"

.PP
FT232H CBUS EEPROM options - Power Enable# 
.SS "const byte FTD2XX_NET\&.FTDI\&.FT_232H_CBUS_OPTIONS\&.FT_CBUS_RXLED = 0x01"

.PP
FT232H CBUS EEPROM options - Rx LED 
.SS "const byte FTD2XX_NET\&.FTDI\&.FT_232H_CBUS_OPTIONS\&.FT_CBUS_SLEEP = 0x05"

.PP
FT232H CBUS EEPROM options - Sleep 
.SS "const byte FTD2XX_NET\&.FTDI\&.FT_232H_CBUS_OPTIONS\&.FT_CBUS_TRISTATE = 0x00"

.PP
FT232H CBUS EEPROM options - Tristate 
.SS "const byte FTD2XX_NET\&.FTDI\&.FT_232H_CBUS_OPTIONS\&.FT_CBUS_TXDEN = 0x09"

.PP
FT232H CBUS EEPROM options - Tx Data Enable 
.SS "const byte FTD2XX_NET\&.FTDI\&.FT_232H_CBUS_OPTIONS\&.FT_CBUS_TXLED = 0x02"

.PP
FT232H CBUS EEPROM options - Tx LED 
.SS "const byte FTD2XX_NET\&.FTDI\&.FT_232H_CBUS_OPTIONS\&.FT_CBUS_TXRXLED = 0x03"

.PP
FT232H CBUS EEPROM options - Tx and Rx LED 

.SH "Author"
.PP 
Generated automatically by Doxygen for BSL430\&.NET from the source code\&.
