.TH "FTD2XX_NET.FTDI.FT_PARITY" 3 "Sat Jun 22 2019" "Version 1.2.1" "BSL430.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FTD2XX_NET.FTDI.FT_PARITY \- Permitted parity values for \fBFTDI\fP devices  

.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const byte \fBFT_PARITY_NONE\fP = 0x00"
.br
.RI "No parity "
.ti -1c
.RI "const byte \fBFT_PARITY_ODD\fP = 0x01"
.br
.RI "Odd parity "
.ti -1c
.RI "const byte \fBFT_PARITY_EVEN\fP = 0x02"
.br
.RI "Even parity "
.ti -1c
.RI "const byte \fBFT_PARITY_MARK\fP = 0x03"
.br
.RI "Mark parity "
.ti -1c
.RI "const byte \fBFT_PARITY_SPACE\fP = 0x04"
.br
.RI "Space parity "
.in -1c
.SH "Detailed Description"
.PP 
Permitted parity values for \fBFTDI\fP devices 


.SH "Member Data Documentation"
.PP 
.SS "const byte FTD2XX_NET\&.FTDI\&.FT_PARITY\&.FT_PARITY_EVEN = 0x02"

.PP
Even parity 
.SS "const byte FTD2XX_NET\&.FTDI\&.FT_PARITY\&.FT_PARITY_MARK = 0x03"

.PP
Mark parity 
.SS "const byte FTD2XX_NET\&.FTDI\&.FT_PARITY\&.FT_PARITY_NONE = 0x00"

.PP
No parity 
.SS "const byte FTD2XX_NET\&.FTDI\&.FT_PARITY\&.FT_PARITY_ODD = 0x01"

.PP
Odd parity 
.SS "const byte FTD2XX_NET\&.FTDI\&.FT_PARITY\&.FT_PARITY_SPACE = 0x04"

.PP
Space parity 

.SH "Author"
.PP 
Generated automatically by Doxygen for BSL430\&.NET from the source code\&.
