.TH "FTD2XX_NET.FTDI.FT_PURGE" 3 "Sat Jun 22 2019" "Version 1.2.1" "BSL430.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FTD2XX_NET.FTDI.FT_PURGE \- Purge buffer constant definitions  

.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const byte \fBFT_PURGE_RX\fP = 0x01"
.br
.RI "Purge Rx buffer "
.ti -1c
.RI "const byte \fBFT_PURGE_TX\fP = 0x02"
.br
.RI "Purge Tx buffer "
.in -1c
.SH "Detailed Description"
.PP 
Purge buffer constant definitions 


.SH "Member Data Documentation"
.PP 
.SS "const byte FTD2XX_NET\&.FTDI\&.FT_PURGE\&.FT_PURGE_RX = 0x01"

.PP
Purge Rx buffer 
.SS "const byte FTD2XX_NET\&.FTDI\&.FT_PURGE\&.FT_PURGE_TX = 0x02"

.PP
Purge Tx buffer 

.SH "Author"
.PP 
Generated automatically by Doxygen for BSL430\&.NET from the source code\&.
