.TH "FTD2XX_NET.FTDI.FT_MODEM_STATUS" 3 "Sat Jun 22 2019" "Version 1.2.1" "BSL430.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FTD2XX_NET.FTDI.FT_MODEM_STATUS \- Modem status bit definitions  

.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const byte \fBFT_CTS\fP = 0x10"
.br
.RI "Clear To Send (CTS) modem status "
.ti -1c
.RI "const byte \fBFT_DSR\fP = 0x20"
.br
.RI "Data Set Ready (DSR) modem status "
.ti -1c
.RI "const byte \fBFT_RI\fP = 0x40"
.br
.RI "Ring Indicator (RI) modem status "
.ti -1c
.RI "const byte \fBFT_DCD\fP = 0x80"
.br
.RI "Data Carrier Detect (DCD) modem status "
.in -1c
.SH "Detailed Description"
.PP 
Modem status bit definitions 


.SH "Member Data Documentation"
.PP 
.SS "const byte FTD2XX_NET\&.FTDI\&.FT_MODEM_STATUS\&.FT_CTS = 0x10"

.PP
Clear To Send (CTS) modem status 
.SS "const byte FTD2XX_NET\&.FTDI\&.FT_MODEM_STATUS\&.FT_DCD = 0x80"

.PP
Data Carrier Detect (DCD) modem status 
.SS "const byte FTD2XX_NET\&.FTDI\&.FT_MODEM_STATUS\&.FT_DSR = 0x20"

.PP
Data Set Ready (DSR) modem status 
.SS "const byte FTD2XX_NET\&.FTDI\&.FT_MODEM_STATUS\&.FT_RI = 0x40"

.PP
Ring Indicator (RI) modem status 

.SH "Author"
.PP 
Generated automatically by Doxygen for BSL430\&.NET from the source code\&.
