.TH "libftdinet.ftdi_context" 3 "Sat Jun 22 2019" "Version 1.2.1" "BSL430.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libftdinet.ftdi_context
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "IntPtr \fBusb_dev\fP"
.br
.ti -1c
.RI "int \fBusb_read_timeout\fP"
.br
.ti -1c
.RI "int \fBusb_write_timeout\fP"
.br
.ti -1c
.RI "ChipType \fBtype\fP"
.br
.ti -1c
.RI "int \fBbaudrate\fP"
.br
.ti -1c
.RI "byte \fBbitbang_enabled\fP"
.br
.ti -1c
.RI "IntPtr \fBreadbuffer\fP"
.br
.ti -1c
.RI "uint \fBreadbuffer_offset\fP"
.br
.ti -1c
.RI "uint \fBreadbuffer_remaining\fP"
.br
.ti -1c
.RI "uint \fBreadbuffer_chunksize\fP"
.br
.ti -1c
.RI "uint \fBwritebuffer_chunksize\fP"
.br
.ti -1c
.RI "int \fBiface\fP"
.br
.ti -1c
.RI "int \fBindex\fP"
.br
.ti -1c
.RI "int \fBin_ep\fP"
.br
.ti -1c
.RI "int \fBout_ep\fP"
.br
.ti -1c
.RI "byte \fBbitbang_mode\fP"
.br
.ti -1c
.RI "int \fBeeprom_size\fP"
.br
.ti -1c
.RI "IntPtr \fBerror_str\fP"
.br
.ti -1c
.RI "IntPtr \fBasync_usb_buffer\fP"
.br
.ti -1c
.RI "uint \fBasync_usb_buffe_rsize\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for BSL430\&.NET from the source code\&.
