.TH "RJCP.IO.Ports.PortDescription" 3 "Sat Jun 22 2019" "Version 1.2.1" "BSL430.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RJCP.IO.Ports.PortDescription \- A class containing information about a serial port\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPortDescription\fP (string port, string description)"
.br
.RI "Constructor\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBPort\fP\fC [get, set]\fP"
.br
.RI "The name of the port "
.ti -1c
.RI "string \fBDescription\fP\fC [get, set]\fP"
.br
.RI "Description about the serial port\&. "
.in -1c
.SH "Detailed Description"
.PP 
A class containing information about a serial port\&. 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "RJCP\&.IO\&.Ports\&.PortDescription\&.PortDescription (string port, string description)"

.PP
Constructor\&. 
.PP
\fBParameters:\fP
.RS 4
\fIport\fP The name of the port\&.
.br
\fIdescription\fP Description about the serial port\&.
.RE
.PP

.SH "Property Documentation"
.PP 
.SS "string RJCP\&.IO\&.Ports\&.PortDescription\&.Description\fC [get]\fP, \fC [set]\fP"

.PP
Description about the serial port\&. 
.SS "string RJCP\&.IO\&.Ports\&.PortDescription\&.Port\fC [get]\fP, \fC [set]\fP"

.PP
The name of the port 

.SH "Author"
.PP 
Generated automatically by Doxygen for BSL430\&.NET from the source code\&.
