.TH "RJCP.IO.Ports.SerialErrorReceivedEventArgs" 3 "Sat Jun 22 2019" "Version 1.2.1" "BSL430.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RJCP.IO.Ports.SerialErrorReceivedEventArgs \- EventArgs for ErrorReceived\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits EventArgs\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSerialErrorReceivedEventArgs\fP (\fBSerialError\fP eventType)"
.br
.RI "Constructor "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBSerialError\fP \fBEventType\fP\fC [get]\fP"
.br
.RI "The event type for ErrorReceived\&. "
.in -1c
.SH "Detailed Description"
.PP 
EventArgs for ErrorReceived\&. 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "RJCP\&.IO\&.Ports\&.SerialErrorReceivedEventArgs\&.SerialErrorReceivedEventArgs (\fBSerialError\fP eventType)"

.PP
Constructor 
.PP
\fBParameters:\fP
.RS 4
\fIeventType\fP Event that occurred\&.
.RE
.PP

.SH "Property Documentation"
.PP 
.SS "\fBSerialError\fP RJCP\&.IO\&.Ports\&.SerialErrorReceivedEventArgs\&.EventType\fC [get]\fP"

.PP
The event type for ErrorReceived\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for BSL430\&.NET from the source code\&.
