.TH "RJCP.IO.Ports.Native.Windows.CommErrorEventArgs" 3 "Sat Jun 22 2019" "Version 1.2.1" "BSL430.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RJCP.IO.Ports.Native.Windows.CommErrorEventArgs
.SH SYNOPSIS
.br
.PP
.PP
Inherits EventArgs\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCommErrorEventArgs\fP (NativeMethods\&.ComStatErrors eventType)"
.br
.RI "Constructor\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "NativeMethods\&.ComStatErrors \fBEventType\fP\fC [get]\fP"
.br
.RI "NativeMethods\&.ComStatErrors result\&. "
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RJCP\&.IO\&.Ports\&.Native\&.Windows\&.CommErrorEventArgs\&.CommErrorEventArgs (NativeMethods\&.ComStatErrors eventType)"

.PP
Constructor\&. 
.PP
\fBParameters:\fP
.RS 4
\fIeventType\fP NativeMethods\&.ComStatErrors result\&.
.RE
.PP

.SH "Property Documentation"
.PP 
.SS "NativeMethods\&.ComStatErrors RJCP\&.IO\&.Ports\&.Native\&.Windows\&.CommErrorEventArgs\&.EventType\fC [get]\fP"

.PP
NativeMethods\&.ComStatErrors result\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for BSL430\&.NET from the source code\&.
