.TH "RJCP.IO.Ports.Native.Windows" 3 "Sat Jun 22 2019" "Version 1.2.1" "BSL430.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RJCP.IO.Ports.Native.Windows
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCommErrorEventArgs\fP"
.br
.ti -1c
.RI "class \fBCommEventArgs\fP"
.br
.ti -1c
.RI "class \fBCommModemStatus\fP"
.br
.RI "Abstracts the Win32 API GetCommModemStatus()\&. "
.ti -1c
.RI "class \fBCommOverlappedIo\fP"
.br
.ti -1c
.RI "class \fBCommProperties\fP"
.br
.RI "Abstracts the Win32 API GetCommProperties()\&. "
.ti -1c
.RI "class \fBCommState\fP"
.br
.RI "Abstracts the Win32 API \fBGetCommState()\fP and \fBSetCommState()\fP\&. "
.ti -1c
.RI "class \fBNativeMethods\fP"
.br
.ti -1c
.RI "class \fBSafeNativeMethods\fP"
.br
.ti -1c
.RI "class \fBUnsafeNativeMethods\fP"
.br
.ti -1c
.RI "class \fBWinError\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBDtrControl\fP { \fBDtrControl\&.Disable\fP = 0, \fBDtrControl\&.Enable\fP = 1, \fBDtrControl\&.Handshake\fP = 2 }"
.br
.RI "Type of DTR (Data Terminal Ready) control to use\&. "
.ti -1c
.RI "enum \fBRtsControl\fP { \fBRtsControl\&.Disable\fP = 0, \fBRtsControl\&.Enable\fP = 1, \fBRtsControl\&.Handshake\fP = 2, \fBRtsControl\&.Toggle\fP = 3 }"
.br
.RI "RTS (Request to Send) to use\&. "
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBRJCP\&.IO\&.Ports\&.Native\&.Windows\&.DtrControl\fP\fC [strong]\fP"

.PP
Type of DTR (Data Terminal Ready) control to use\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIDisable \fP\fP
Disable DTR line\&. 
.TP
\fB\fIEnable \fP\fP
Enable DTR line\&. 
.TP
\fB\fIHandshake \fP\fP
DTR Handshaking\&. 
.SS "enum \fBRJCP\&.IO\&.Ports\&.Native\&.Windows\&.RtsControl\fP\fC [strong]\fP"

.PP
RTS (Request to Send) to use\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIDisable \fP\fP
Disable RTS line\&. 
.TP
\fB\fIEnable \fP\fP
Enable the RTS line\&. 
.TP
\fB\fIHandshake \fP\fP
RTS Handshaking\&. 
.TP
\fB\fIToggle \fP\fP
RTS Toggling\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for BSL430\&.NET from the source code\&.
