.TH "RJCP.IO.LocalAsync" 3 "Sat Jun 22 2019" "Version 1.2.1" "BSL430.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RJCP.IO.LocalAsync \- Provides a local implementation of an IAsyncResult  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBRJCP\&.IO\&.LocalAsync< T >\fP\&.
.SH "Detailed Description"
.PP 
Provides a local implementation of an IAsyncResult 



.SH "Author"
.PP 
Generated automatically by Doxygen for BSL430\&.NET from the source code\&.
