.TH "RJCP.IO.Ports.Native.UnixNativeSerial" 3 "Sat Jun 22 2019" "Version 1.2.1" "BSL430.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RJCP.IO.Ports.Native.UnixNativeSerial \- \fBWindows\fP implementation for a \fBNative\fP Serial connection\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBRJCP\&.IO\&.Ports\&.Native\&.INativeSerial\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "string [] \fBGetPortNames\fP ()"
.br
.RI "Gets an array of serial port names for the current computer\&. "
.ti -1c
.RI "\fBPortDescription\fP [] \fBGetPortDescriptions\fP ()"
.br
.RI "Gets an array of serial port names and descriptions for the current computer\&. "
.ti -1c
.RI "void \fBDiscardInBuffer\fP ()"
.br
.RI "Discards the input queue buffer of the driver\&. "
.ti -1c
.RI "void \fBDiscardOutBuffer\fP ()"
.br
.RI "Discards the output queue buffer of the driver\&. "
.ti -1c
.RI "void \fBGetPortSettings\fP ()"
.br
.RI "Gets the port settings and updates the properties of the object\&. "
.ti -1c
.RI "void \fBSetPortSettings\fP ()"
.br
.RI "Writes the settings of the serial port as set in this object\&. "
.ti -1c
.RI "void \fBOpen\fP ()"
.br
.RI "Opens the serial port specified by \fBPortName\fP\&. "
.ti -1c
.RI "void \fBClose\fP ()"
.br
.RI "Closes the serial port\&. "
.ti -1c
.RI "\fBSerialBuffer\fP \fBCreateSerialBuffer\fP (int readBuffer, int writeBuffer)"
.br
.RI "Creates the serial buffer suitable for monitoring\&. "
.ti -1c
.RI "void \fBStartMonitor\fP (\fBSerialBuffer\fP buffer, string name)"
.br
.RI "Start the monitor thread, that will watch over the serial port\&. "
.ti -1c
.RI "void \fBDispose\fP ()"
.br
.RI "Performs application-defined tasks associated with freeing, releasing, or resetting unmanaged resources\&. "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBOnDataReceived\fP (object sender, \fBSerialDataReceivedEventArgs\fP args)"
.br
.ti -1c
.RI "virtual void \fBOnCommError\fP (object sender, \fBSerialErrorReceivedEventArgs\fP args)"
.br
.ti -1c
.RI "virtual void \fBOnPinChanged\fP (object sender, \fBSerialPinChangedEventArgs\fP args)"
.br
.ti -1c
.RI "virtual void \fBDispose\fP (bool disposing)"
.br
.RI "Releases unmanaged and - optionally - managed resources\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBVersion\fP\fC [get]\fP"
.br
.RI "Gets the version of the implementation in use\&. "
.ti -1c
.RI "string \fBPortName\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the port device path\&. "
.ti -1c
.RI "int \fBBaudRate\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the baud rate\&. "
.ti -1c
.RI "int \fBDataBits\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the data bits\&. "
.ti -1c
.RI "\fBParity\fP \fBParity\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the parity\&. "
.ti -1c
.RI "\fBStopBits\fP \fBStopBits\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the stop bits\&. "
.ti -1c
.RI "bool \fBDiscardNull\fP\fC [get, set]\fP"
.br
.RI "Gets or sets a value if null bytes should be discarded or not\&. "
.ti -1c
.RI "byte \fBParityReplace\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the parity replace byte\&. "
.ti -1c
.RI "bool \fBTxContinueOnXOff\fP\fC [get, set]\fP"
.br
.RI "Gets or sets a value indicating whether transmission should still be sent when the input buffer is full and if the XOff character has been sent\&. "
.ti -1c
.RI "int \fBXOffLimit\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the XOff limit input when the XOff character should be sent\&. "
.ti -1c
.RI "int \fBXOnLimit\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the XOn limit when the input buffer is below when the XOn character should be sent\&. "
.ti -1c
.RI "bool \fBBreakState\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the break state of the serial port\&. "
.ti -1c
.RI "int \fBDriverInQueue\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the driver input queue size\&. "
.ti -1c
.RI "int \fBDriverOutQueue\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the driver output queue size\&. "
.ti -1c
.RI "int \fBBytesToRead\fP\fC [get]\fP"
.br
.RI "Gets the number of bytes in the input queue of the driver not yet read (not any managed buffers)\&. "
.ti -1c
.RI "int \fBBytesToWrite\fP\fC [get]\fP"
.br
.RI "Gets the number of bytes in the output buffer of the driver still to write (not any managed buffers)\&. "
.ti -1c
.RI "bool \fBCDHolding\fP\fC [get]\fP"
.br
.RI "Gets the state of the Carrier Detect pin on the serial port\&. "
.ti -1c
.RI "bool \fBCtsHolding\fP\fC [get]\fP"
.br
.RI "Gets the state of the Clear To Send pin on the serial port\&. "
.ti -1c
.RI "bool \fBDsrHolding\fP\fC [get]\fP"
.br
.RI "Gets the state of the Data Set Ready pin on the serial port\&. "
.ti -1c
.RI "bool \fBRingHolding\fP\fC [get]\fP"
.br
.RI "Gets the state of the Ring Indicator pin on the serial port\&. "
.ti -1c
.RI "bool \fBDtrEnable\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the Data Terminal Ready pin of the serial port\&. "
.ti -1c
.RI "bool \fBRtsEnable\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the Request To Send pin of the serial port\&. "
.ti -1c
.RI "\fBHandshake\fP \fBHandshake\fP\fC [get, set]\fP"
.br
.RI "Gets or sets the handshake to use on the serial port\&. "
.ti -1c
.RI "bool \fBIsOpen\fP\fC [get]\fP"
.br
.RI "Gets a value indicating whether the serial port has been opened\&. "
.ti -1c
.RI "bool \fBIsRunning\fP\fC [get]\fP"
.br
.RI "Gets a value indicating whether the thread for monitoring the serial port is running\&. "
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "EventHandler< \fBSerialDataReceivedEventArgs\fP > \fBDataReceived\fP"
.br
.RI "Occurs when data is received, or the EOF character is detected by the driver\&. "
.ti -1c
.RI "EventHandler< \fBSerialErrorReceivedEventArgs\fP > \fBErrorReceived\fP"
.br
.RI "Occurs when an error condition is detected\&. "
.ti -1c
.RI "EventHandler< \fBSerialPinChangedEventArgs\fP > \fBPinChanged\fP"
.br
.RI "Occurs when modem pin changes are detected\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBWindows\fP implementation for a \fBNative\fP Serial connection\&. 


.PP
\fBSee also:\fP
.RS 4
\fBRJCP\&.IO\&.Ports\&.Native\&.INativeSerial\fP
.PP
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void RJCP\&.IO\&.Ports\&.Native\&.UnixNativeSerial\&.Close ()"

.PP
Closes the serial port\&. Closing the serial port invalidates actions that can be done to the serial port, but it does not prevent the serial port from being reopened 
.PP
Implements \fBRJCP\&.IO\&.Ports\&.Native\&.INativeSerial\fP\&.
.SS "\fBSerialBuffer\fP RJCP\&.IO\&.Ports\&.Native\&.UnixNativeSerial\&.CreateSerialBuffer (int readBuffer, int writeBuffer)"

.PP
Creates the serial buffer suitable for monitoring\&. 
.PP
\fBParameters:\fP
.RS 4
\fIreadBuffer\fP The read buffer size to allocate\&.
.br
\fIwriteBuffer\fP The write buffer size to allocate\&.
.RE
.PP
\fBReturns:\fP
.RS 4
A serial buffer object that can be given to \fBStartMonitor\fP
.RE
.PP

.PP
Implements \fBRJCP\&.IO\&.Ports\&.Native\&.INativeSerial\fP\&.
.SS "void RJCP\&.IO\&.Ports\&.Native\&.UnixNativeSerial\&.DiscardInBuffer ()"

.PP
Discards the input queue buffer of the driver\&. 
.PP
Implements \fBRJCP\&.IO\&.Ports\&.Native\&.INativeSerial\fP\&.
.SS "void RJCP\&.IO\&.Ports\&.Native\&.UnixNativeSerial\&.DiscardOutBuffer ()"

.PP
Discards the output queue buffer of the driver\&. 
.PP
Implements \fBRJCP\&.IO\&.Ports\&.Native\&.INativeSerial\fP\&.
.SS "void RJCP\&.IO\&.Ports\&.Native\&.UnixNativeSerial\&.Dispose ()"

.PP
Performs application-defined tasks associated with freeing, releasing, or resetting unmanaged resources\&. 
.SS "virtual void RJCP\&.IO\&.Ports\&.Native\&.UnixNativeSerial\&.Dispose (bool disposing)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Releases unmanaged and - optionally - managed resources\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdisposing\fP \fCtrue\fP to release both managed and unmanaged resources; \fCfalse\fP to release only unmanaged resources\&.
.RE
.PP

.SS "\fBPortDescription\fP [] RJCP\&.IO\&.Ports\&.Native\&.UnixNativeSerial\&.GetPortDescriptions ()"

.PP
Gets an array of serial port names and descriptions for the current computer\&. This method uses the \fBWindows\fP Management Interface to obtain its information\&. Therefore, the list may be different to the list obtained using the \fBGetPortNames()\fP method which uses other techniques\&. 
.PP
On \fBWindows\fP 7, this method shows to return normal COM ports, but not those associated with a modem driver\&.
.PP
\fBReturns:\fP
.RS 4
An array of serial ports for the current computer\&.
.RE
.PP

.PP
Implements \fBRJCP\&.IO\&.Ports\&.Native\&.INativeSerial\fP\&.
.SS "string [] RJCP\&.IO\&.Ports\&.Native\&.UnixNativeSerial\&.GetPortNames ()"

.PP
Gets an array of serial port names for the current computer\&. 
.PP
\fBReturns:\fP
.RS 4
An array of serial port names for the current computer\&.
.RE
.PP

.PP
Implements \fBRJCP\&.IO\&.Ports\&.Native\&.INativeSerial\fP\&.
.SS "void RJCP\&.IO\&.Ports\&.Native\&.UnixNativeSerial\&.GetPortSettings ()"

.PP
Gets the port settings and updates the properties of the object\&. 
.PP
Implements \fBRJCP\&.IO\&.Ports\&.Native\&.INativeSerial\fP\&.
.SS "void RJCP\&.IO\&.Ports\&.Native\&.UnixNativeSerial\&.Open ()"

.PP
Opens the serial port specified by \fBPortName\fP\&. Opening the serial port does not set any settings (such as baud rate, etc\&.) 
.PP
Implements \fBRJCP\&.IO\&.Ports\&.Native\&.INativeSerial\fP\&.
.SS "void RJCP\&.IO\&.Ports\&.Native\&.UnixNativeSerial\&.SetPortSettings ()"

.PP
Writes the settings of the serial port as set in this object\&. 
.PP
Implements \fBRJCP\&.IO\&.Ports\&.Native\&.INativeSerial\fP\&.
.SS "void RJCP\&.IO\&.Ports\&.Native\&.UnixNativeSerial\&.StartMonitor (\fBSerialBuffer\fP buffer, string name)"

.PP
Start the monitor thread, that will watch over the serial port\&. 
.PP
\fBParameters:\fP
.RS 4
\fIbuffer\fP The buffer structure that should be used to read data into and write data from\&.
.br
\fIname\fP The name of the thread to use\&.
.RE
.PP

.PP
Implements \fBRJCP\&.IO\&.Ports\&.Native\&.INativeSerial\fP\&.
.SH "Property Documentation"
.PP 
.SS "int RJCP\&.IO\&.Ports\&.Native\&.UnixNativeSerial\&.BaudRate\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the baud rate\&. The baud rate\&. 
.SS "bool RJCP\&.IO\&.Ports\&.Native\&.UnixNativeSerial\&.BreakState\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the break state of the serial port\&. \fCtrue\fP if in the break state; otherwise, \fCfalse\fP\&. 
.SS "int RJCP\&.IO\&.Ports\&.Native\&.UnixNativeSerial\&.BytesToRead\fC [get]\fP"

.PP
Gets the number of bytes in the input queue of the driver not yet read (not any managed buffers)\&. The number of bytes in the driver queue for reading\&. If this value is not supported, zero is returned\&. 
.SS "int RJCP\&.IO\&.Ports\&.Native\&.UnixNativeSerial\&.BytesToWrite\fC [get]\fP"

.PP
Gets the number of bytes in the output buffer of the driver still to write (not any managed buffers)\&. The number of bytes in the driver queue for writing\&. If this value is not supported, zero is returned\&. 
.SS "bool RJCP\&.IO\&.Ports\&.Native\&.UnixNativeSerial\&.CDHolding\fC [get]\fP"

.PP
Gets the state of the Carrier Detect pin on the serial port\&. \fCtrue\fP if carrier detect pin is active; otherwise, \fCfalse\fP\&. 
.SS "bool RJCP\&.IO\&.Ports\&.Native\&.UnixNativeSerial\&.CtsHolding\fC [get]\fP"

.PP
Gets the state of the Clear To Send pin on the serial port\&. \fCtrue\fP if the clear to send pin is active; otherwise, \fCfalse\fP\&. 
.SS "int RJCP\&.IO\&.Ports\&.Native\&.UnixNativeSerial\&.DataBits\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the data bits\&. The data bits\&. 
.SS "bool RJCP\&.IO\&.Ports\&.Native\&.UnixNativeSerial\&.DiscardNull\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets a value if null bytes should be discarded or not\&. \fCtrue\fP if null bytes should be discarded; otherwise, \fCfalse\fP\&. 
.SS "int RJCP\&.IO\&.Ports\&.Native\&.UnixNativeSerial\&.DriverInQueue\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the driver input queue size\&. The driver input queue size\&. 
.PP
This method is typically available with \fBWindows\fP API only\&. 
.SS "int RJCP\&.IO\&.Ports\&.Native\&.UnixNativeSerial\&.DriverOutQueue\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the driver output queue size\&. The driver output queue size\&. 
.PP
This method is typically available with \fBWindows\fP API only\&. 
.SS "bool RJCP\&.IO\&.Ports\&.Native\&.UnixNativeSerial\&.DsrHolding\fC [get]\fP"

.PP
Gets the state of the Data Set Ready pin on the serial port\&. \fCtrue\fP if data set ready pin is active; otherwise, \fCfalse\fP\&. 
.SS "bool RJCP\&.IO\&.Ports\&.Native\&.UnixNativeSerial\&.DtrEnable\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the Data Terminal Ready pin of the serial port\&. \fCtrue\fP if data terminal pin is active; otherwise, \fCfalse\fP\&. 
.PP
This pin only has an effect if handshaking for DTR/DTS is disabled\&. 
.SS "\fBHandshake\fP RJCP\&.IO\&.Ports\&.Native\&.UnixNativeSerial\&.Handshake\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the handshake to use on the serial port\&. The handshake mode to use on the serial port\&. 
.SS "bool RJCP\&.IO\&.Ports\&.Native\&.UnixNativeSerial\&.IsOpen\fC [get]\fP"

.PP
Gets a value indicating whether the serial port has been opened\&. \fCtrue\fP if this instance is open; otherwise, \fCfalse\fP\&. 
.PP
This property only indicates if the port has been opened and that the internal handle is valid\&. 
.SS "bool RJCP\&.IO\&.Ports\&.Native\&.UnixNativeSerial\&.IsRunning\fC [get]\fP"

.PP
Gets a value indicating whether the thread for monitoring the serial port is running\&. \fCtrue\fP if this instance is running; otherwise, \fCfalse\fP\&. 
.PP
This property differs slightly from \fBIsOpen\fP, as this returns status if the monitoring thread for reading/writing data is actually running\&. If the thread is not running for whatever reason, we can expect no data updates in the buffer provided to \fBStartMonitor(SerialBuffer, string)\fP\&. 
.SS "\fBParity\fP RJCP\&.IO\&.Ports\&.Native\&.UnixNativeSerial\&.Parity\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the parity\&. The parity\&. 
.SS "byte RJCP\&.IO\&.Ports\&.Native\&.UnixNativeSerial\&.ParityReplace\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the parity replace byte\&. The byte to use on parity errors\&. 
.SS "string RJCP\&.IO\&.Ports\&.Native\&.UnixNativeSerial\&.PortName\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the port device path\&. The port device path\&. 
.SS "bool RJCP\&.IO\&.Ports\&.Native\&.UnixNativeSerial\&.RingHolding\fC [get]\fP"

.PP
Gets the state of the Ring Indicator pin on the serial port\&. \fCtrue\fP if ring indicator state is active; otherwise, \fCfalse\fP\&. 
.SS "bool RJCP\&.IO\&.Ports\&.Native\&.UnixNativeSerial\&.RtsEnable\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the Request To Send pin of the serial port\&. \fCtrue\fP if [RTS enable]; otherwise, \fCfalse\fP\&. 
.PP
This pin only has an effect if the handshaking for RTS/CTS is disabled\&. 
.SS "\fBStopBits\fP RJCP\&.IO\&.Ports\&.Native\&.UnixNativeSerial\&.StopBits\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the stop bits\&. The stop bits\&. 
.SS "bool RJCP\&.IO\&.Ports\&.Native\&.UnixNativeSerial\&.TxContinueOnXOff\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets a value indicating whether transmission should still be sent when the input buffer is full and if the XOff character has been sent\&. \fCtrue\fP if transmission should continue after the input buffer is within \fBXOffLimit\fP bytes of being full and the driver has sent the XOff character; otherwise, \fCfalse\fP that transmission should stop and only continue when the input buffer is within \fBXOnLimit\fP bytes of being empty and the driver has sent the XOn character\&. 
.SS "string RJCP\&.IO\&.Ports\&.Native\&.UnixNativeSerial\&.Version\fC [get]\fP"

.PP
Gets the version of the implementation in use\&. The version of the implementation in use\&. 
.SS "int RJCP\&.IO\&.Ports\&.Native\&.UnixNativeSerial\&.XOffLimit\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the XOff limit input when the XOff character should be sent\&. The XOff buffer limit\&. 
.SS "int RJCP\&.IO\&.Ports\&.Native\&.UnixNativeSerial\&.XOnLimit\fC [get]\fP, \fC [set]\fP"

.PP
Gets or sets the XOn limit when the input buffer is below when the XOn character should be sent\&. The XOn buffer limit\&. 
.SH "Event Documentation"
.PP 
.SS "EventHandler<\fBSerialDataReceivedEventArgs\fP> RJCP\&.IO\&.Ports\&.Native\&.UnixNativeSerial\&.DataReceived"

.PP
Occurs when data is received, or the EOF character is detected by the driver\&. 
.SS "EventHandler<\fBSerialErrorReceivedEventArgs\fP> RJCP\&.IO\&.Ports\&.Native\&.UnixNativeSerial\&.ErrorReceived"

.PP
Occurs when an error condition is detected\&. 
.SS "EventHandler<\fBSerialPinChangedEventArgs\fP> RJCP\&.IO\&.Ports\&.Native\&.UnixNativeSerial\&.PinChanged"

.PP
Occurs when modem pin changes are detected\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for BSL430\&.NET from the source code\&.
