.TH "RJCP.IO.Ports.InternalApplicationException" 3 "Sat Jun 22 2019" "Version 1.2.1" "BSL430.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RJCP.IO.Ports.InternalApplicationException \- Indicates an unexpected internal error occurred in the application\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInternalApplicationException\fP ()"
.br
.RI "Initializes a new instance of the \fBInternalApplicationException\fP class\&. "
.ti -1c
.RI "\fBInternalApplicationException\fP (string message)"
.br
.RI "Initializes a new instance of the \fBInternalApplicationException\fP class\&. "
.ti -1c
.RI "\fBInternalApplicationException\fP (string message, Exception innerException)"
.br
.RI "Initializes a new instance of the \fBInternalApplicationException\fP class\&. "
.in -1c
.SH "Detailed Description"
.PP 
Indicates an unexpected internal error occurred in the application\&. 

The InternalApplicationError indicates a programming error in the application\&. Such an error should never occur and always indicates a bug in the application itself\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RJCP\&.IO\&.Ports\&.InternalApplicationException\&.InternalApplicationException ()"

.PP
Initializes a new instance of the \fBInternalApplicationException\fP class\&. 
.SS "RJCP\&.IO\&.Ports\&.InternalApplicationException\&.InternalApplicationException (string message)"

.PP
Initializes a new instance of the \fBInternalApplicationException\fP class\&. 
.PP
\fBParameters:\fP
.RS 4
\fImessage\fP The message that describes the error\&.
.RE
.PP

.SS "RJCP\&.IO\&.Ports\&.InternalApplicationException\&.InternalApplicationException (string message, Exception innerException)"

.PP
Initializes a new instance of the \fBInternalApplicationException\fP class\&. 
.PP
\fBParameters:\fP
.RS 4
\fImessage\fP The error message that explains the reason for the exception\&.
.br
\fIinnerException\fP The exception that is the cause of the current exception, or a null reference (Nothing in Visual Basic) if no inner exception is specified\&.
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for BSL430\&.NET from the source code\&.
