.TH "RJCP.IO.Ports.SerialPinChangedEventArgs" 3 "Sat Jun 22 2019" "Version 1.2.1" "BSL430.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RJCP.IO.Ports.SerialPinChangedEventArgs \- EventArgs for PinChanged\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits EventArgs\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSerialPinChangedEventArgs\fP (\fBSerialPinChange\fP eventType)"
.br
.RI "Constructor\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBSerialPinChange\fP \fBEventType\fP\fC [get]\fP"
.br
.RI "The event type for ErrorReceived\&. "
.in -1c
.SH "Detailed Description"
.PP 
EventArgs for PinChanged\&. 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "RJCP\&.IO\&.Ports\&.SerialPinChangedEventArgs\&.SerialPinChangedEventArgs (\fBSerialPinChange\fP eventType)"

.PP
Constructor\&. 
.PP
\fBParameters:\fP
.RS 4
\fIeventType\fP Event that occurred\&.
.RE
.PP

.SH "Property Documentation"
.PP 
.SS "\fBSerialPinChange\fP RJCP\&.IO\&.Ports\&.SerialPinChangedEventArgs\&.EventType\fC [get]\fP"

.PP
The event type for ErrorReceived\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for BSL430\&.NET from the source code\&.
