.TH "RJCP.IO.Ports.Native.Windows.CommProperties" 3 "Sat Jun 22 2019" "Version 1.2.1" "BSL430.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RJCP.IO.Ports.Native.Windows.CommProperties \- Abstracts the Win32 API GetCommProperties()\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBGetCommProperties\fP ()"
.br
.ti -1c
.RI "bool \fBIsValidDataBits\fP (int databits)"
.br
.RI "Check if the number of data bits is settable\&. "
.ti -1c
.RI "bool \fBIsValidStopBits\fP (\fBStopBits\fP stopbits)"
.br
.RI "Check if the number of stop bits is settable\&. "
.ti -1c
.RI "bool \fBIsValidParity\fP (\fBParity\fP parity)"
.br
.RI "Check if the parity is supported\&. "
.ti -1c
.RI "bool \fBIsValidBaud\fP (int baudrate)"
.br
.RI "Check if the baud rate value given is settable\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBMaxTxQueue\fP\fC [get]\fP"
.br
.ti -1c
.RI "int \fBMaxRxQueue\fP\fC [get]\fP"
.br
.ti -1c
.RI "int \fBCurrentTxQueue\fP\fC [get]\fP"
.br
.ti -1c
.RI "int \fBCurrentRxQueue\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBIsSettableParity\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBIsSettableBaud\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBIsSettableDataBits\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBIsSettableStopbits\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBIsSettableHandshaking\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBIsSettableParityCheck\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBIsSettableRlsd\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBIsDtrDsrSupported\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBIsRtsCtsSupported\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBIsRlsdSupported\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBIsParityCheckSupported\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBIsXOnXOffSupported\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBIsXCharSupported\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBIsTotalTimeoutsSupported\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBIsIntervalTimeoutsSupported\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBIsSpecialCharsSupported\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBIs16BitSupported\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBIsUnspecifiedType\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBIsRs232Type\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBIsParallelPortType\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBIsRs422Type\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBIsRs423Type\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBIsRs499Type\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBIsModemType\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBIsFaxType\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Abstracts the Win32 API GetCommProperties()\&. 


.SH "Member Function Documentation"
.PP 
.SS "bool RJCP\&.IO\&.Ports\&.Native\&.Windows\&.CommProperties\&.IsValidBaud (int baudrate)"

.PP
Check if the baud rate value given is settable\&. This function relies on the \fCdwSettableBaud\fP parameter\&. It does not rely on the \fCdwMaxBaud\fP parameter as if they don't match, then this is an inconsistency in the \fBWindows\fP serial driver\&. 
.PP
\fBParameters:\fP
.RS 4
\fIbaudrate\fP The baud rate to check for\&.
.RE
.PP
\fBReturns:\fP
.RS 4
\fBtrue\fP if the baud rate is indicated to be supported\&.
.RE
.PP

.SS "bool RJCP\&.IO\&.Ports\&.Native\&.Windows\&.CommProperties\&.IsValidDataBits (int databits)"

.PP
Check if the number of data bits is settable\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdatabits\fP The number of data bits the user wants to set\&.
.RE
.PP
\fBReturns:\fP
.RS 4
\fBtrue\fP if the number of data bits is indicated as supported\&.
.RE
.PP

.SS "bool RJCP\&.IO\&.Ports\&.Native\&.Windows\&.CommProperties\&.IsValidParity (\fBParity\fP parity)"

.PP
Check if the parity is supported\&. 
.PP
\fBParameters:\fP
.RS 4
\fIparity\fP The parity the user wants to set\&.
.RE
.PP
\fBReturns:\fP
.RS 4
\fBtrue\fP if the parity is indicated as supported\&.
.RE
.PP

.SS "bool RJCP\&.IO\&.Ports\&.Native\&.Windows\&.CommProperties\&.IsValidStopBits (\fBStopBits\fP stopbits)"

.PP
Check if the number of stop bits is settable\&. 
.PP
\fBParameters:\fP
.RS 4
\fIstopbits\fP The number of stop bits the user wants to set\&.
.RE
.PP
\fBReturns:\fP
.RS 4
\fBtrue\fP if the number of stop bits is indicated as supported\&.
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for BSL430\&.NET from the source code\&.
