.TH "System.IO.Ports.SerialPort" 3 "Sat Jun 22 2019" "Version 1.2.1" "BSL430.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
System.IO.Ports.SerialPort \- Class \fBSerialPort\fP compatibility layer for \&.NET Stanard 1\&.5  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static string [] \fBGetPortNames\fP ()"
.br
.RI "Gets the port names\&. "
.in -1c
.SH "Detailed Description"
.PP 
Class \fBSerialPort\fP compatibility layer for \&.NET Stanard 1\&.5 


.SH "Member Function Documentation"
.PP 
.SS "static string [] System\&.IO\&.Ports\&.SerialPort\&.GetPortNames ()\fC [static]\fP"

.PP
Gets the port names\&. 
.PP
\fBReturns:\fP
.RS 4
An empty array\&.
.RE
.PP
.PP
As \&.NET Standard doesn't contain this functionality, we provide it for the compiler and do nothing\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for BSL430\&.NET from the source code\&.
