.TH "System.EntryPointNotFoundException" 3 "Sat Jun 22 2019" "Version 1.2.1" "BSL430.NET" \" -*- nroff -*-
.ad l
.nh
.SH NAME
System.EntryPointNotFoundException \- The exception that is thrown when an attempt to load a class fails due to the absence of an entry method\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEntryPointNotFoundException\fP ()"
.br
.RI "Initializes a new instance of the \fBEntryPointNotFoundException\fP class\&. "
.ti -1c
.RI "\fBEntryPointNotFoundException\fP (string message)"
.br
.RI "Initializes a new instance of the \fBEntryPointNotFoundException\fP class\&. "
.ti -1c
.RI "\fBEntryPointNotFoundException\fP (string message, Exception innerException)"
.br
.RI "Initializes a new instance of the \fBEntryPointNotFoundException\fP class\&. "
.in -1c
.SH "Detailed Description"
.PP 
The exception that is thrown when an attempt to load a class fails due to the absence of an entry method\&. 

This method is intended as a drop in replacement for the equivalent exception in \&.NET\&. Unfortunately, \&.NET Standard 1\&.6 and earlier do not contain this exception, even though P/Invoke on Windows certainly raises this exception\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "System\&.EntryPointNotFoundException\&.EntryPointNotFoundException ()"

.PP
Initializes a new instance of the \fBEntryPointNotFoundException\fP class\&. 
.SS "System\&.EntryPointNotFoundException\&.EntryPointNotFoundException (string message)"

.PP
Initializes a new instance of the \fBEntryPointNotFoundException\fP class\&. 
.PP
\fBParameters:\fP
.RS 4
\fImessage\fP The message that describes the error\&.
.RE
.PP

.SS "System\&.EntryPointNotFoundException\&.EntryPointNotFoundException (string message, Exception innerException)"

.PP
Initializes a new instance of the \fBEntryPointNotFoundException\fP class\&. 
.PP
\fBParameters:\fP
.RS 4
\fImessage\fP The error message that explains the reason for the exception\&.
.br
\fIinnerException\fP The exception that is the cause of the current exception, or a null reference (Nothing in Visual Basic) if no inner exception is specified\&.
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for BSL430\&.NET from the source code\&.
